# Introduction

This notebook aims to understand and visualize static GTFS data reported from the TTC
Specifically we would like to visualize Route 29, a bus route that is known to have significantly high trip times

You can find the exact data source used in this project below: https://open.toronto.ca/dataset/merged-gtfs-ttc-routes-and-schedules/

# Data Modeling

Before we dig into the data itself, we will start off by understanding the inherent structure of the data (the data model). The GTFS specifciation is a global standard used to structure transit data reported by transit agencies. Specifically the GTFS specifies an array of CSV text files each representing different types of transit information (i.e. route/trip information, schedule information, geo-shape information etc.). Each CSV text file relate to each other through a relational schema.

A relational schema representing the GTFS data reported by the TTC can be found below:

![GTFS_STATIC_Relational_Model](/Users/devrajsolanki/Documents/TAL/GTFS_STATIC_Relational_Model.jpeg)

# Data Preprocessing

GTFS feeds can be quite messy at times, containing incomplete, invalid and inconsistent data.
Thankfully there is significant effort to validate the quality of GTFS feed data.
 
We will be using validation techniques suggested from Mobility Data (https://gtfs-validator.mobilitydata.org/rules.html) as well as common 
Data Preprocessing/Cleaning techniques.

### Data Loading

In [795]:
import pandas as pd

In [796]:
stops = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/stops.txt")
routes = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/routes.txt")
trips = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/trips.txt")
stop_times = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/stop_times.txt")
shapes = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/shapes.txt")
calendar = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/calendar.txt")
agency = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/agency.txt")
calendar_dates = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/calendar_dates.txt")
route_types = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/route_types.txt")
feed_info = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/feed_info.txt")

/var/folders/b2/y50nhjkn7554xcj0cffkg3m80000gn/T/ipykernel_73779/2009019488.py:3: DtypeWarning: Columns (4,7) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/trips.txt")
/var/folders/b2/y50nhjkn7554xcj0cffkg3m80000gn/T/ipykernel_73779/2009019488.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  stop_times = pd.read_csv("/Users/devrajsolanki/Documents/Complete_GTFS/stop_times.txt")

### Data Understanding and Cleaning 

The inclusion of a stop_times.txt file means this is a schedule-based feed (define specific arrival and departure times for every trip at every stop)

In [797]:
# lets look at the shape of each dataframe to understand the size of the data

print("Shape of stops dataframe:", stops.shape)
print("Shape of routes dataframe:", routes.shape)
print("Shape of trips dataframe:", trips.shape)
print("Shape of stop_times dataframe:", stop_times.shape)
print("Shape of shapes dataframe:", shapes.shape)
print("Shape of calendar dataframe:", calendar.shape)
print("Shape of agency dataframe:", agency.shape)
print("Shape of calendar_dates dataframe:", calendar_dates.shape)
print("Shape of route_types dataframe:", route_types.shape)
print("Shape of feed_info dataframe:", feed_info.shape)

# It seems that the number of records for each file matches logic; there should be a lot of stop_times records since each trip has multiple 
# stops and there should be fewer routes than trips, etc. This is a good sign that the feed is complete.

Shape of stops dataframe: (9423, 13)
Shape of routes dataframe: (230, 9)
Shape of trips dataframe: (135412, 9)
Shape of stop_times dataframe: (4283994, 10)
Shape of shapes dataframe: (1020671, 5)
Shape of calendar dataframe: (8, 10)
Shape of agency dataframe: (1, 9)
Shape of calendar_dates dataframe: (9, 3)
Shape of route_types dataframe: (679, 5)
Shape of feed_info dataframe: (1, 6)

#### Stops.txt

In [798]:
# lets look at the data types of each column in each dataframe to identify if the feed is clean/recorded properly

print("Data types of stops dataframe:")
print(stops.dtypes)
print("-" * 50)

Data types of stops dataframe:
stop_id                  int64
stop_code                int64
stop_name               object
stop_desc              float64
stop_lat               float64
stop_lon               float64
zone_id                float64
stop_url               float64
location_type            int64
parent_station         float64
stop_timezone          float64
wheelchair_boarding      int64
level_id               float64
dtype: object
--------------------------------------------------

In [799]:
# its weird that stop_desc is a float and not a string/object, so lets look at the unique values in the column
print("Unique values in stop_desc column of stops dataframe:")
print(stops["stop_desc"].unique())

# so it seems that the TTC Feed leaves out/excludes stop description, so lets remove the column from the dataframe
stops = stops.drop(columns=["stop_desc"])

print("Updated Data types of stops dataframe:")
print(stops.dtypes)
print("-" * 50)

Unique values in stop_desc column of stops dataframe:
[nan]
Updated Data types of stops dataframe:
stop_id                  int64
stop_code                int64
stop_name               object
stop_lat               float64
stop_lon               float64
zone_id                float64
stop_url               float64
location_type            int64
parent_station         float64
stop_timezone          float64
wheelchair_boarding      int64
level_id               float64
dtype: object
--------------------------------------------------

In [800]:
# everything checks out, lets now look at the distribution of values for each column as well
# for the primary key, we will look at the number of unique values and their frequencies
# for integer columns we will look at the range and possibly mean
# for float values we will look at the range (float values usually will represent geographical coordinates so taking the mean/median doesnt make sense)
# for object/string values we will look at the unique values and their frequencies/mode

# stop_id
print("Distribution of stop_id column in stops dataframe:")
print(stops["stop_id"].value_counts())
print("-" * 50)

# There are 9423 unique stop_ids which matches the number of records in the stop dataframe so there are no duplicate primary keys

# stop_code
print("Distribution of stop_code column in stops dataframe:")
print(stops["stop_code"].value_counts())
print("-" * 50)

# There also seems to be 9423 unique stop_codes per record

Distribution of stop_id column in stops dataframe:
stop_id
1        1
8449     1
8430     1
8431     1
8432     1
        ..
4742     1
4743     1
4745     1
4746     1
16803    1
Name: count, Length: 9423, dtype: int64
--------------------------------------------------
Distribution of stop_code column in stops dataframe:
stop_code
7978     1
5831     1
12194    1
990      1
2395     1
        ..
3959     1
8896     1
1876     1
7166     1
16803    1
Name: count, Length: 9423, dtype: int64
--------------------------------------------------

In [801]:
# stop_name
print("Distribution of stop_name column in stops dataframe:")
print(stops["stop_name"].value_counts())
print("-" * 50)

# filter stop_name for "Centennial College Bus Terminal"
centennial_stops = stops[stops["stop_name"] == "Centennial College Bus Terminal"]
print("Filtered stops for 'Centennial College Bus Terminal':")
print(centennial_stops)

# So it seems that some stops share the same name but have different stop_ids and stop_codes and even slightly different coordinates. 
# This makes sense since there can be multiple platforms at the same general location (Centennial college has 4 bus platforms).

Distribution of stop_name column in stops dataframe:
stop_name
Centennial College Bus Terminal                                 4
Humber College Bus Terminal                                     4
The Queensway at South Kingsway                                 4
Bathurst St at King St West                                     4
Bathurst St at Niagara St                                       4
                                                               ..
Millwood Rd at Southvale Dr                                     1
Belfield Rd at City View Dr                                     1
Faywood Blvd at Invermay Ave                                    1
Queens Quay West at Bathurst St East Side Billy Bishop Airpo    1
McCowan Rd at Highway 401                                       1
Name: count, Length: 7782, dtype: int64
--------------------------------------------------
Filtered stops for 'Centennial College Bus Terminal':
      stop_id  stop_code                        stop_name   stop_lat  \
8489    18829      15884  Centennial College Bus Terminal  43.786406
8490    18830      15886  Centennial College Bus Terminal  43.786119
8493    18837      15885  Centennial College Bus Terminal  43.786271
8744    42364      15887  Centennial College Bus Terminal  43.785912

       stop_lon  zone_id  stop_url  location_type  parent_station  \
8489 -79.229692      NaN       NaN              0             NaN
8490 -79.229493      NaN       NaN              0             NaN
8493 -79.229592      NaN       NaN              0             NaN
8744 -79.229343      NaN       NaN              0             NaN

      stop_timezone  wheelchair_boarding  level_id
8489            NaN                    1       NaN
8490            NaN                    1       NaN
8493            NaN                    1       NaN
8744            NaN                    1       NaN

In [802]:
# stop_lat
print("Distribution of stop_lat column in stops dataframe:")
print("Range of stop_lat:", stops["stop_lat"].min(), "to", stops["stop_lat"].max())
print("-" * 50)

# stop_lon
print("Distribution of stop_lon column in stops dataframe:")
print("Range of stop_lon:", stops["stop_lon"].min(), "to", stops["stop_lon"].max())
print("-" * 50)

# Toronto lies around 43.6425, -79.387222 [wikipedia] so the stop coordinates seem to be within the expected range for Toronto.

Distribution of stop_lat column in stops dataframe:
Range of stop_lat: 43.59181 to 43.90975
--------------------------------------------------
Distribution of stop_lon column in stops dataframe:
Range of stop_lon: -79.649908 to -79.123111
--------------------------------------------------

In [803]:
# zone_id
print("Distribution of zone_id column in stops dataframe:")
print(stops["zone_id"].value_counts())
print("-" * 50)

# It seems that the zone_id column is not used in the feed since all values are NaN,

# stop_url
print("Distribution of stop_url column in stops dataframe:")
print(stops["stop_url"].value_counts())
print("-" * 50)

# It seems that the stop_url column is not used in the feed since all values are NaN

# remove the zone_id and stop_url columns since they are not used in the feed
stops = stops.drop(columns=["zone_id", "stop_url"])

print("Updated Data types of stops dataframe:")
print(stops.dtypes)
print("-" * 50)

Distribution of zone_id column in stops dataframe:
Series([], Name: count, dtype: int64)
--------------------------------------------------
Distribution of stop_url column in stops dataframe:
Series([], Name: count, dtype: int64)
--------------------------------------------------
Updated Data types of stops dataframe:
stop_id                  int64
stop_code                int64
stop_name               object
stop_lat               float64
stop_lon               float64
location_type            int64
parent_station         float64
stop_timezone          float64
wheelchair_boarding      int64
level_id               float64
dtype: object
--------------------------------------------------

In [804]:
# location_type
print("Distribution of location_type column in stops dataframe:")
print(stops["location_type"].value_counts())
print("-" * 50)

# so it seems that the TTC reported all stops as location_type 0 (stops/platforms); this means that stations, entrances/exits are 
# not included in the feed data; just the points where the bus/subway etc. picks up/drops off passengers

# parent_station
print("Distribution of parent_station column in stops dataframe:")
print(stops["parent_station"].value_counts())
print("-" * 50)

# hence parent_station has all values are NaN since stations are not included in the feed data 

# drop parent_station column since it is not used in the feed
stops = stops.drop(columns=["parent_station"])

print("Updated Data types of stops dataframe:")
print(stops.dtypes)
print("-" * 50)

Distribution of location_type column in stops dataframe:
location_type
0    9423
Name: count, dtype: int64
--------------------------------------------------
Distribution of parent_station column in stops dataframe:
Series([], Name: count, dtype: int64)
--------------------------------------------------
Updated Data types of stops dataframe:
stop_id                  int64
stop_code                int64
stop_name               object
stop_lat               float64
stop_lon               float64
location_type            int64
stop_timezone          float64
wheelchair_boarding      int64
level_id               float64
dtype: object
--------------------------------------------------

In [805]:
# stop_timezone
print("Range of stop_timezone column in stops dataframe:")
print(stops["stop_timezone"].min(), stops["stop_timezone"].max())

# it seems that the stop_timezone column is not used in the feed since all values are NaN, so we will drop the column from the dataframe
stops = stops.drop(columns=["stop_timezone"])

# wheelchair_boarding
print("Distribution of wheelchair_boarding column in stops dataframe:")
print(stops["wheelchair_boarding"].value_counts())
print("-" * 50)

# so it looks like most stops support wheelchair boarding (value 1), but some do not (value 2), and there are a few that have unknown wheelchair boarding status (value 0) 

# level_id
print("Distribution of level_id column in stops dataframe:")
print(stops["level_id"].value_counts())
print("-" * 50)

# it seems that the level_id column is not used in the feed since all values are NaN, so we will drop the column from the dataframe
stops = stops.drop(columns=["level_id"])

print("Updated Data types of stops dataframe:")
print(stops.dtypes)
print("-" * 50)

Range of stop_timezone column in stops dataframe:
nan nan
Distribution of wheelchair_boarding column in stops dataframe:
wheelchair_boarding
1    8020
2    1396
0       7
Name: count, dtype: int64
--------------------------------------------------
Distribution of level_id column in stops dataframe:
Series([], Name: count, dtype: int64)
--------------------------------------------------
Updated Data types of stops dataframe:
stop_id                  int64
stop_code                int64
stop_name               object
stop_lat               float64
stop_lon               float64
location_type            int64
wheelchair_boarding      int64
dtype: object
--------------------------------------------------

In [806]:
# lets look at the presence of null values and empty strings in the rows of the stop 

print("Number of null values in each column of stops dataframe:")
print(stops.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of stops dataframe:")
object_columns = stops.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (stops[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

# overall, looks like the feed for stops has complete data

Number of null values in each column of stops dataframe:
stop_id                0
stop_code              0
stop_name              0
stop_lat               0
stop_lon               0
location_type          0
wheelchair_boarding    0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of stops dataframe:
stop_name: 0
--------------------------------------------------

#### Routes.txt

We will now perform the same cleaning process to the routes table

In [807]:
# print data types of routes dataframe

print("Data types of routes dataframe:")
print(routes.dtypes)
print("-" * 50)

Data types of routes dataframe:
route_id              int64
agency_id             int64
route_short_name      int64
route_long_name      object
route_desc          float64
route_type            int64
route_url           float64
route_color          object
route_text_color     object
dtype: object
--------------------------------------------------

In [808]:
# lets first identify columns that are not used in the feed and drop them from the dataframe to simplify our analysis
# we can identify these columns by looking at the unique values in each column and seeing if they are all NaN or empty strings

for col in routes.columns:
    unique_values = routes[col].unique()
    print(f"Unique values in {col} column of routes dataframe:")
    print(unique_values)
    print("-" * 50)

Unique values in route_id column of routes dataframe:
[ 10 100 101 102 103 104 105 106 107 108 109  11 110 111 112 113 114 115
 116 117 118 119  12 120 121 122 123 124 125 126 127 129  13 130 131 132
 133 134 135  14 149  15 151 154 156 158  16 160 161 162 164 165 166 167
 168 169  17 171  18 184 185 189  19 191  20 203  21  22  23  24  25  26
  27  28  29  30 300 301 304 305 306 307  31 310 312 315 316  32 320 322
 324 325 329  33 334 335 336 337 339  34 340 341 343  35 352 353 354  36
 363 365  37  38 384 385 386  39 395 396  40  41  42  43  44  45  46  47
  48  49  50 501 503 504 505 506 507 508 509  51 510 511 512  52  53  54
  55  57  59  60  61  62  63  64  65  66  67  68  69   7  70  71  72  73
  74  75  76  77  78  79   8  80 805  82  83 830  84  85  86  87  88  89
   9  90 900 902 903 904 905 906  91  92 924 925 927 929  93 935 937 938
 939  94 941 944 945  95 952 953 954  96 960 968  97  98 984 985 986 989
  99 995 996   1   2   4 400 402 403 404 405 406   5   6]
--------------------------------------------------
Unique values in agency_id column of routes dataframe:
[1]
--------------------------------------------------
Unique values in route_short_name column of routes dataframe:
[ 10 100 101 102 103 104 105 106 107 108 109  11 110 111 112 113 114 115
 116 117 118 119  12 120 121 122 123 124 125 126 127 129  13 130 131 132
 133 134 135  14 149  15 151 154 156 158  16 160 161 162 164 165 166 167
 168 169  17 171  18 184 185 189  19 191  20 203  21  22  23  24  25  26
  27  28  29  30 300 301 304 305 306 307  31 310 312 315 316  32 320 322
 324 325 329  33 334 335 336 337 339  34 340 341 343  35 352 353 354  36
 363 365  37  38 384 385 386  39 395 396  40  41  42  43  44  45  46  47
  48  49  50 501 503 504 505 506 507 508 509  51 510 511 512  52  53  54
  55  57  59  60  61  62  63  64  65  66  67  68  69   7  70  71  72  73
  74  75  76  77  78  79   8  80 805  82  83 830  84  85  86  87  88  89
   9  90 900 902 903 904 905 906  91  92 924 925 927 929  93 935 937 938
 939  94 941 944 945  95 952 953 954  96 960 968  97  98 984 985 986 989
  99 995 996   1   2   4 400 402 403 404 405 406   5   6]
--------------------------------------------------
Unique values in route_long_name column of routes dataframe:
['Van Horne' 'Flemingdon Park' 'Downsview Park' 'Markham Rd'
 'Mount Pleasant North' 'Faywood' 'Dufferin North' 'Sentinel'
 'Alness-Chesswood' 'Driftwood' 'Ranee' 'Bayview' 'Islington South'
 'East Mall' 'West Mall' 'Danforth' 'Queens Quay East' 'Silver Hills'
 'Morningside' 'Birchmount South' 'Thistle Down' 'Torbarrie' 'Kingston Rd'
 'Calvington' 'Esplanade-River' 'Graydon Hall' 'Sherway' 'Sunnybrook'
 'Drewry' 'Christie' 'Davenport' 'McCowan North' 'Avenue Rd' 'Middlefield'
 'Nugget' 'Milner' 'Neilson' 'Progress' 'Gerrard' 'Glencairn'
 'Etobicoke-Bloor' 'Evans' 'Leslie North' 'Curran Hall' 'Millwood'
 'Trethewey' 'McCowan' 'Bathurst North' 'Rogers Rd' 'Lawrence-Donway'
 'Castlefield' 'Weston Rd North' 'Toryork' 'Pharmacy North' 'Symington'
 'Huntingwood' 'Birchmount' 'Mount Dennis' 'Caledonia' 'Ancaster Park'
 'Sheppard Central' 'Stockyards' 'Bay' 'Underhill' 'Cliffside' 'High Park'
 'Brimley' 'Coxwell' 'Dawes' 'Victoria Park' 'Don Mills' 'Dupont'
 'Jane South' 'Bayview South' 'Dufferin' 'High Park North'
 'Bloor-Danforth' 'Queen' 'King' 'Dundas' 'Carlton' 'Bathurst' 'Greenwood'
 'Spadina' 'St Clair' "Evans-Brown's Line" 'Kingston Rd-McCowan'
 'Eglinton West' 'Yonge' 'Forest Hill' 'Eglinton' 'Jane' 'Finch West'
 'Islington' 'Finch East' 'Junction' 'Keele' 'Kennedy' 'Lawrence West'
 'Steeles' 'Lawrence East' 'Ossington' 'Parliament' 'Highland Creek'
 'Sheppard West' 'Sheppard East' 'Scarborough' 'York Mills' 'Wilson'
 'Junction-Dundas West' 'Cummer' 'Kipling South' 'Kipling' 'Martin Grove'
 'Lansdowne' 'Rathburn' 'Bloor West' 'Burnhamthorpe' 'Long Branch'
 'Lake Shore' 'Harbourfront' 'Leslie' 'Steeles East' 'Warren Park'
 'Midland' 'Maple Leaf' 'Steeles West' 'Avenue Rd North' 'Mortimer' 'Main'
 'Prince Edward' 'Pharmacy' 'Warden' 'Warden South' "O'Connor" 'Runnymede'
 'Pape' 'Royal York' 'Mount Pleasant' 'Sherbourne' 'Royal York South'
 'Swansea' 'St Andrews' 'Scarlett Rd' 'Broadview' 'Queensway'
 'Line 5 Shuttle' 'Rosedale' 'Jones' 'Henry Kelsey - Middlefield'
 'Cosburn' 'South Leaside' 'Weston' 'Bellamy' 'Vaughan' 'Airport Express'
 'Markham Rd Express' 'Kennedy Stn-Scarborough Express'
 'Sheppard-Kennedy Express' 'Eglinton East Express'
 'Airport-Humber College Express' 'Woodbine' 'Woodbine South'
 'Victoria Park Express' 'Don Mills Express' 'Highway 27 Express'
 'Dufferin Express' 'Parkview Hills' 'Jane Express' 'Islington Express'
 'Highland Creek Express' 'Finch Express' 'Wellesley' 'Keele Express'
 'Kipling South Express' 'Kipling Express' 'Lawrence West Express'
 'Steeles East Express' 'Lawrence East Express' 'Steeles West Express'
 'Warden Express' 'Willowdale-Senlac' 'Sheppard West Express'
 'Sheppard East Express' 'Scarborough Express' 'Weston Express' 'Arrow Rd'
 'York Mills Express' 'Wilson Express' 'Yonge-University Line'
 'Bloor-Danforth Line' 'Sheppard Line' 'Lawrence Manor' 'Parkdale'
 'South Don Mills' 'East York' 'Etobicoke' 'Scarborough-Guildwood'
 'Eglinton Line' 'Finch West Line']
--------------------------------------------------
Unique values in route_desc column of routes dataframe:
[nan]
--------------------------------------------------
Unique values in route_type column of routes dataframe:
[3 0 1]
--------------------------------------------------
Unique values in route_url column of routes dataframe:
[nan]
--------------------------------------------------
Unique values in route_color column of routes dataframe:
['ED1C24' 'E472AC' '0054A6' 'FF8000' '00A651' 'D5C82B' '008000' 'B300B3'
 '6D6E71' '808080']
--------------------------------------------------
Unique values in route_text_color column of routes dataframe:
['FFFFFF' '000000']
--------------------------------------------------

In [809]:
# drop route_desc and route_url columns since they are not used in the feed
routes = routes.drop(columns=["route_desc", "route_url"])

print("Updated Data types of routes dataframe:")
print(routes.dtypes)
print("-" * 50)

Updated Data types of routes dataframe:
route_id             int64
agency_id            int64
route_short_name     int64
route_long_name     object
route_type           int64
route_color         object
route_text_color    object
dtype: object
--------------------------------------------------

In [810]:
# each dytype seems to be appropriate for the type of data in each column
# lets now look at the distribution of values for each column as well

# for the primary key, we will look at the number of unique values and their frequencies
# for integer columns we will look at the range and possibly mean
# for float values we will look at the range (float values usually will represent geographical coordinates so taking the mean/median doesnt make sense)
# for object/string values we will look at the unique values and their frequencies/mode

for col in routes.columns:
    if col == "route_id":
        print(f"Distribution of {col} column in routes dataframe:")
        print(routes[col].value_counts(dropna=False))
        print("-" * 50)
    elif routes[col].dtype == "int64":
        print(f"Range of {col} column in routes dataframe: {routes[col].min()} to {routes[col].max()}")
        print("-" * 50)
        print(f"Distribution of {col} column in routes dataframe:")
        print(routes[col].value_counts(dropna=False))
        print("-" * 50)
    elif routes[col].dtype == "float64":
        print(f"Range of {col} column in routes dataframe: {routes[col].min()} to {routes[col].max()}")
        print("-" * 50)
    elif routes[col].dtype == "object":
        print(f"Distribution of {col} column in routes dataframe:")
        print(routes[col].value_counts(dropna=False))
        print("-" * 50)

Distribution of route_id column in routes dataframe:
route_id
10     1
55     1
59     1
60     1
61     1
      ..
306    1
307    1
31     1
310    1
6      1
Name: count, Length: 230, dtype: int64
--------------------------------------------------
Range of agency_id column in routes dataframe: 1 to 1
--------------------------------------------------
Distribution of agency_id column in routes dataframe:
agency_id
1    230
Name: count, dtype: int64
--------------------------------------------------
Range of route_short_name column in routes dataframe: 1 to 996
--------------------------------------------------
Distribution of route_short_name column in routes dataframe:
route_short_name
10     1
55     1
59     1
60     1
61     1
      ..
306    1
307    1
31     1
310    1
6      1
Name: count, Length: 230, dtype: int64
--------------------------------------------------
Distribution of route_long_name column in routes dataframe:
route_long_name
Bathurst            3
Lawrence East       2
Victoria Park       2
Islington           2
Kingston Rd         2
                   ..
Ancaster Park       1
Sheppard Central    1
Stockyards          1
Bay                 1
Finch West Line     1
Name: count, Length: 200, dtype: int64
--------------------------------------------------
Range of route_type column in routes dataframe: 0 to 3
--------------------------------------------------
Distribution of route_type column in routes dataframe:
route_type
3    208
0     19
1      3
Name: count, dtype: int64
--------------------------------------------------
Distribution of route_color column in routes dataframe:
route_color
ED1C24    156
0054A6     33
00A651     28
6D6E71      6
FF8000      2
E472AC      1
D5C82B      1
008000      1
B300B3      1
808080      1
Name: count, dtype: int64
--------------------------------------------------
Distribution of route_text_color column in routes dataframe:
route_text_color
FFFFFF    229
000000      1
Name: count, dtype: int64
--------------------------------------------------

In [811]:
# There are some obervations we can make from this

# 1) There are 230 unique rows in the routes dataframe; each row seems to correspnd to a unique value of route_id (230 unique route_ids). This is a good sign
#    that the primary key is unique

# 2) agency_id contains only 1 unique value (1) meaning that the only transit agency managing routes in this feed is the TTC

# 3) it seems each route has a unique route_short_name (equal in value to route_id) but some routes share the same route_long_name
#    This makes sense since the same bus routes, for example, can have different route numbers but end up at the same destination
#.   For example route 307 and 511 are different routes but both end up at Bathurst station, so they share the same route_long_name

# 4) There are 3 unique route_types in the TTC feed; 3 (bus), 1 (subway), and 4 (streetcar) which makes sense since the TTC operates these 3 modes of transportation
#    There are more bus routes than subway and streetcar routes which also makes sense since the bus network is usually more extensive than subway and streetcar networks in a city
#.   The 3 subway routes line up with the 3 subway lines in Toronto (Yonge-University-Spadina, Bloor-Danforth, and Sheppard) which is another good sign that the feed is accurate and complete

In [812]:
# looking at routes with route_long_name = "Bathurst"
print("Routes with route_long_name 'Bathurst':")
print(routes[routes["route_long_name"] == "Bathurst"])
print("-" * 50)

# looking at routes with route_type = 1 (subway)
print("Routes with route_type 1 (subway):")
print(routes[routes["route_type"] == 1])
print("-" * 50)

Routes with route_long_name 'Bathurst':
     route_id  agency_id  route_short_name route_long_name  route_type  \
81        307          1               307        Bathurst           3
139       511          1               511        Bathurst           0
157         7          1                 7        Bathurst           3

    route_color route_text_color
81       0054A6           FFFFFF
139      ED1C24           FFFFFF
157      ED1C24           FFFFFF
--------------------------------------------------
Routes with route_type 1 (subway):
     route_id  agency_id  route_short_name        route_long_name  route_type  \
219         1          1                 1  Yonge-University Line           1
220         2          1                 2    Bloor-Danforth Line           1
221         4          1                 4          Sheppard Line           1

    route_color route_text_color
219      D5C82B           000000
220      008000           FFFFFF
221      B300B3           FFFFFF
--------------------------------------------------

In [813]:
# lets look at the presence of null values and empty strings in the rows of the routes dataframe

print("Number of null values in each column of routes dataframe:")
print(routes.isnull().sum())
print("-" * 50)

# lets look at the presence of null values and empty strings in the rows of the routes dataframe
print("Number of empty strings in object dtype columns of routes dataframe:")
object_columns = routes.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (routes[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

# overall, looks like the feed for routes has complete data

Number of null values in each column of routes dataframe:
route_id            0
agency_id           0
route_short_name    0
route_long_name     0
route_type          0
route_color         0
route_text_color    0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of routes dataframe:
route_long_name: 0
route_color: 0
route_text_color: 0
--------------------------------------------------

#### Trips.txt

In [814]:
# print data types of trips dataframe

print("Data types of trips dataframe:")
print(trips.dtypes)
print("-" * 50)

Data types of trips dataframe:
trip_id                   int64
route_id                  int64
service_id                int64
trip_headsign            object
trip_short_name          object
direction_id              int64
block_id                  int64
shape_id                 object
wheelchair_accessible     int64
dtype: object
--------------------------------------------------

In [815]:
# lets first identify columns that are not used in the feed and drop them from the dataframe to simplify our analysis
# we can identify these columns by looking at the unique values in each column and seeing if they are all NaN or empty strings

for col in trips.columns:
    unique_values = trips[col].unique()
    print(f"Unique values in {col} column of trips dataframe:")
    print(unique_values)
    print("-" * 50)

Unique values in trip_id column of trips dataframe:
[106986020 118048020 102340020 ... 133251418 133251419 133251420]
--------------------------------------------------
Unique values in route_id column of trips dataframe:
[ 10 100 101 102 103 104 105 106 107 108 109  11 110 111 112 113 114 115
 116 117 118 119  12 120 121 122 123 124 125 126 127 129  13 130 131 132
 133 134 135  14 149  15 151 154 156 158  16 160 161 162 164 165 166 167
 168 169  17 171  18 184 185 189  19 191  20 203  21  22  23  24  25  26
  27  28  29  30 300 301 304 305 306 307  31 310 312 315 316  32 320 322
 324 325 329  33 334 335 336 337 339  34 340 341 343  35 352 353 354  36
 363 365  37  38 384 385 386  39 395 396  40  41  42  43  44  45  46  47
  48  49  50 501 503 504 505 506 507 508 509  51 510 511 512  52  53  54
  55  57  59  60  61  62  63  64  65  66  67  68  69   7  70  71  72  73
  74  75  76  77  78  79   8  80 805  82  83 830  84  85  86  87  88  89
   9  90 900 902 903 904 905 906  91  92 924 925 927 929  93 935 937 938
 939  94 941 944 945  95 952 953 954  96 960 968  97  98 984 985 986 989
  99 995 996 400 402 403 404 405 406   1   2   4   5   6]
--------------------------------------------------
Unique values in service_id column of trips dataframe:
[   1    3    2    5 4401 4501 7001    4]
--------------------------------------------------
Unique values in trip_headsign column of trips dataframe:
['East - 10 Van Horne towards Victoria Park' 'Not In Service'
 'West - 10 Van Horne towards Don Mills Station'
 'North - 100A Flemingdon Park towards Don Valley Station'
 'North - 100B Flemingdon Park towards Don Valley Station via Linkwood'
 'South - 100A Flemingdon Park towards Broadview Station'
 'South - 100B Flemingdon Park towards Broadview Station via Linkwood'
 'North - 101 Downsview Park towards Finch West Station via Downsview Park Station'
 'North - 101S Downsview Park Short Turn towards Downsview Park Station'
 'North - 101S Downsview Park Short Turn towards Stanley Greene'
 'South - 101A Downsview Park towards Stanley Greene via Downsview Park Station'
 'South - 101B Downsview Park towards Wilson Station via Stanley Greene and Downsview Park Station'
 'North - 102A Markham Rd towards Progress / Centennial College'
 'North - 102B Markham Rd towards Steeles'
 'North - 102C Markham Rd towards Steeles via Dynamic Dr'
 'North - 102D Markham Rd towards Major Mackenzie'
 'North - 102S Markham Rd Short Turn towards Sheppard'
 'South - 102 Markham Rd towards Warden Station'
 'South - 102C Markham Rd towards Warden Station via Dynamic Dr'
 'South - 102S Markham Rd Short Turn towards Markham and Steeles'
 'South - 102S Markham Rd Short Turn towards Sheppard'
 'North - 103 Mount Pleasant North towards Doncliffe'
 'South - 103 Mount Pleasant North towards Eglinton Station'
 'South - 103S Mount Pleasant North Short Turn towards Lawrence'
 'North - 104 Faywood towards Sheppard West Station'
 'South - 104 Faywood towards Wilson Station'
 'North - 105 Dufferin North towards Steeles'
 'South - 105 Dufferin North towards Sheppard West Station'
 'East - 106 Sentinel towards Sheppard West Station'
 'West - 106 Sentinel towards  Pioneer Village Station'
 'North - 107 Alness-Chesswood towards Finch West Station'
 'South - 107 Alness-Chesswood towards Sheppard West Station'
 'East - 108A Driftwood towards Sheppard West Station via Grandravine'
 'East - 108B Driftwood towards Sheppard West Station via Arleta'
 'East - 108S Driftwood Short Turn'
 'West - 108A Driftwood towards Pioneer Village Station via Grandravine'
 'West - 108B Driftwood towards Pioneer Village Station via Arleta'
 'North - 109B Ranee towards Neptune via Flemington'
 'North - 109C Ranee towards Neptune via Varna'
 'North - 109S Ranee Short Turn'
 'South - 109B Ranee towards Cedarvale Station via Flemington'
 'South - 109C Ranee towards Cedarvale Station via Varna'
 'South - 109S Ranee Short Turn towards Lawrence West Station'
 'North - 11A Bayview towards Steeles via Sunnybrook'
 'North - 11C Bayview towards Sunnybrook'
 'South - 11 Bayview towards Davisville Station via Sunnybrook'
 'South - 11 Bayview towards Davisville Station'
 'North - 110A Islington South towards Islington Station via Browns Line and Horner'
 'North - 110B Islington South towards Islington Station via 30th Street and Horner'
 'North - 110C Islington South towards Islington Station'
 'North - 110S Islington South Short Turn towards Islington and Birmingham'
 'South - 110A Islington South towards Long Branch via Horner and Browns Line'
 'South - 110B Islington South towards Long Branch via Horner and 30th Street'
 'South - 110C Islington South towards Kipling and Lake Shore'
 'North - 111 East Mall towards Eglinton'
 'South - 111 East Mall towards Kipling Station'
 'North - 112B West Mall towards Renforth Station'
 'North - 112C West Mall towards Disco Rd via Renforth Station'
 'South - 112 West Mall towards Kipling Station via Eringate And Hwy 427'
 'South - 112 West Mall towards Kipling Station via Renforth Station'
 'South - 112 West Mall towards Kipling Station'
 'South - 112S West Mall Short Turn towards Renforth'
 'East - 113 Danforth towards Kennedy Station'
 'West - 113 Danforth towards Main Street Station'
 'West - 113S Danforth Short Turn towards Birchmount'
 'East - 114 Queens Quay East towards Carlaw via Ookwemin Minising'
 'West - 114 Queens Quay East towards Union Station'
 'East - 115 Silver Hills towards Leslie'
 'West - 115 Silver Hills towards York Mills Station'
 'East - 116 Morningside towards Finch and Morningside'
 'West - 116 Morningside towards Kennedy Station'
 'North - 117 Birchmount South towards Warden Station'
 'North - 117S Birchmount South Short Turn towards Danforth'
 'South - 117 Birchmount South towards Victoria Park Station'
 'East - 118 Thistle Down towards Wilson Station via Tandridge'
 'East - 118 Thistle Down towards Wilson Station'
 'West - 118 Thistle Down towards Thistle Down via Tandridge'
 'West - 118 Thistle Down towards Thistle Down'
 'East - 119A Torbarrie towards Wilson Station via Clayson'
 'East - 119A Torbarrie towards Wilson Station via Torbarrie'
 'East - 119B Torbarrie towards Wilson Station via Clayson'
 'East - 119B Torbarrie towards Wilson Station via Torbarrie'
 'East - 119S Torbarrie Short Turn towards Emery Station'
 'West - 119A Torbarrie towards Arrow Rd via Clayson'
 'West - 119A Torbarrie towards Arrow Rd via Torbarrie'
 'West - 119B Torbarrie towards Milvan via Clayson and Fenmar'
 'West - 119B Torbarrie towards Milvan via Torbarrie and Fenmar'
 'East - 12A Kingston Rd towards Kennedy Station via Variety Village and Brimley'
 'East - 12B Kingston Rd towards Kennedy Station via Brimley'
 'East - 12D Kingston Rd towards U of T Scarborough'
 'West - 12A Kingston Rd towards Victoria Park Station via Brimley and Variety Village'
 'West - 12B Kingston Rd towards Victoria Park Station via Brimley'
 'West - 12D Kingston Rd towards Victoria Park Station'
 'West - 12S Kingston Rd Short Turn towards Bingham Loop'
 'East - 120 Calvington towards Wilson Station'
 'East - 120S Calvington Short Turn towards Jane'
 'West - 120 Calvington towards Sheppard/Jane'
 'East - 121 Esplanade-River Towards Hennick Bridgepoint Hospital'
 'West - 121 Esplanade-River Towards Union Station'
 'East - 122 Graydon Hall towards Roywood via Lesmill'
 'West - 122 Graydon Hall towards York Mills Station'
 'North - 123B Sherway towards Kipling Station via East Mall and Shorncliffe'
 'North - 123C Sherway towards Kipling Station via North Queen and Shorncliffe'
 'North - 123D Sherway towards Kipling Station via East Mall and Shorncliffe'
 'North - 123F Sherway towards Kipling Station via West Mall'
 'South - 123B Sherway towards Long Branch via Shorncliffe and East Mall'
 'South - 123C Sherway towards Long Branch via Shorncliffe and North Queen'
 'South - 123D Sherway towards Sherway Gardens via Shorncliffe and East Mall'
 'South - 123F Sherway towards Sherway Gardens via West Mall'
 'East - 124 Sunnybrook towards Sunnybrook Hospital'
 'West - 124 Sunnybrook towards Lawrence Station'
 'East - 125 Drewry towards Finch Station'
 'East - 125S Drewry Short Turn towards Bathurst'
 'West - 125 Drewry towards Bathurst (Torresdale)'
 'North - 126 Christie towards St Clair West Station'
 'South - 126 Christie towards Christie Station'
 'East - 127 Davenport towards Spadina Station'
 'West - 127 Davenport towards St Clair & Old Weston Rd'
 'North - 129A McCowan North towards Major Mackenzie via Scarborough Centre Stn'
 'North - 129B McCowan North towards Steeles via Scarborough Centre Stn'
 'South - 129 McCowan North towards Kennedy Stn via Scarborough Centre Stn'
 'South - 129S McCowan North Short Turn towards Steeles'
 'North - 13 Avenue Rd towards Eglinton Station'
 'North - 13S Avenue Rd Short Turn towards Museum Station'
 "South - 13A Avenue Rd towards Queen's Park"
 'South - 13B Avenue Rd towards Gerrard'
 'North - 130A Middlefield towards Steeles'
 'North - 130B Middlefield towards Steeles via Maybrook'
 'South - 130A Middlefield towards Scarborough Centre Stn'
 'South - 130B Middlefield towards Scarborough Centre Stn via Maybrook'
 'East - 131 Nugget towards Old Finch/Morningview via Scarborough Centre Stn'
 'West - 131 Nugget towards Kennedy Stn via Scarborough Centre Stn'
 'West - 131S Nugget Short Turn towards Morningside'
 'East - 132 Milner towards McLevin & Hupfield'
 'West - 132 Milner towards Scarborough Centre Stn'
 'West - 132S Milner Short Turn towards Brenyon Way'
 'North - 133 Neilson towards Morningside Heights via Centenary Hospital'
 'North - 133 Neilson towards Morningside Heights via Scarborough Centre Stn and Centenary Hospital'
 'North - 133 Neilson towards Morningside Heights via Scarborough Centre Stn'
 'South - 133 Neilson towards Kennedy Stn via Centenary Hospital and Scarborough Centre Stn'
 'South - 133 Neilson towards Kennedy Stn via Scarborough Centre Stn'
 'North - 134B Progress towards McNicoll via Crow Trail'
 'North - 134B Progress towards McNicoll via Tapscott'
 'North - 134D Progress towards Finch via Centennial College And Crow Trail'
 'North - 134D Progress towards Finch via Centennial College And Tapscott'
 'North - 134D Progress towards Finch via Tapscott'
 'South - 134 Progress towards Scarborough Centre Stn'
 'South - 134D Progress towards Scarborough Centre Stn via Centennial College'
 'East - 135 Gerrard towards Warden Station'
 'West - 135 Gerrard towards Main Street Station'
 'East - 14 Glencairn towards Davisville Station'
 'West - 14 Glencairn Towards Caledonia'
 'East - 149 Etobicoke-Bloor towards Jane Station'
 'West - 149 Etobicoke-Bloor towards Kipling Station'
 'East - 15 Evans towards Royal York Station'
 'West - 15 Evans towards Sherway Gardens'
 'North - 151 Leslie North towards Steeles'
 'South - 151 Leslie North towards Leslie Station'
 'East - 154 Curran Hall towards U of T Scarborough'
 'West - 154 Curran Hall towards Kennedy Station'
 'North - 156 Millwood towards Wicksteed via Laird Station'
 'South - 156 Millwood towards Thorncliffe Park'
 'South - 156S Millwood Short Turn'
 'East - 158 Trethewey towards Keelesdale Station'
 'West - 158 Trethewey towards Weston Rd and Oak'
 'North - 16 McCowan towards Scarborough Centre Stn'
 'South - 16 McCowan towards Warden Station'
 'North - 160 Bathurst North towards Centre Street'
 'South - 160 Bathurst North towards Wilson Station'
 'East - 161 Rogers Rd towards Ossington Station'
 'West - 161 Rogers Rd towards Mount Dennis Station'
 'East - 162 Lawrence-Donway towards Don Valley Station'
 'West - 162 Lawrence-Donway towards Lawrence Station'
 'East - 164 Castlefield towards Cedarvale Station'
 'West - 164 Castlefield towards Mount Dennis Station'
 'East - 165 Weston Rd North towards York Mills Station'
 'East - 165S Weston Rd North Short Turn towards Albion and Weston'
 'East - 165S Weston Rd North Short Turn towards Finch'
 'East - 165S Weston Rd North Short Turn towards Wilson Station'
 'West - 165 Weston Rd North towards Steeles'
 'East - 166 Toryork Short Turn towards Steeles and Islington'
 'East - 166 Toryork towards Pioneer Village Station'
 'West - 166 Toryork towards Milvan'
 'West - 166S Toryork Short Turn towards Emery Station'
 'North - 167A Pharmacy North towards Steeles via Consumers Rd'
 'North - 167B Pharmacy North towards Steeles'
 'South - 167A Pharmacy North towards Don Mills Station via Consumers Rd'
 'South - 167B Pharmacy North towards Don Mills Station'
 'North - 168 Symington towards Mount Dennis Station'
 'South - 168 Symington towards Dundas West Station'
 'East - 169A Huntingwood towards Scarborough Centre Stn via Van Horne'
 'East - 169B Huntingwood towards Scarborough Centre Stn'
 'West - 169A Huntingwood towards Don Mills Station via Van Horne'
 'West - 169B Huntingwood towards Don Mills Station'
 'North - 17A Birchmount towards Highway 7'
 'North - 17B Birchmount towards Steeles via Wintermute'
 'North - 17C Birchmount towards Steeles and Warden'
 'North - 17S Birchmount Short Turn towards Finch'
 'South - 17 Birchmount towards Warden Station'
 'North - 171 Mount Dennis towards Industry Street'
 'North - 171A Mount Dennis towards Industry Street via Mount Dennis Station'
 'South - 171A Mount Dennis towards Jane via Mount Dennis Station'
 'South - 171B Mount Dennis towards Eglinton and Black Creek'
 'South - 171B Mount Dennis towards Mount Dennis Station'
 'North - 18A Caledonia towards Yorkdale Station via Bridgeland'
 'North - 18B Caledonia towards Yorkdale Station via Orfus'
 'South - 18A Caledonia towards Caledonia Station via Bridgeland'
 'South - 18B Caledonia towards Caledonia Station via Orfus'
 'East - 184 Ancaster Park towards Wilson Station'
 'West - 184 Ancaster Park towards De Havilland'
 'East - 185 Sheppard Central towards Don Mills Station'
 'West - 185 Sheppard Central towards Sheppard-Yonge Station'
 'East - 189 Stockyards towards High Park Station via Keele Station'
 'East - 189S Stockyards Short Turn towards St Clair and Gunns'
 'West - 189 Stockyards towards Scarlett Rd'
 'North - 19 Bay towards Dupont' 'South - 19 Bay towards Union Station'
 'North - 191 Underhill towards York Mills'
 'South - 191 Underhill towards Don Valley Station'
 'South - 191S Underhill Short Turn towards Railside'
 'East - 20 Cliffside towards Kennedy Station'
 'West - 20 Cliffside towards Main Street Station'
 'North - 203 High Park towards High Park Stn via Colborne Lodge Dr'
 'South - 203 High Park towards High Park via West Rd'
 'North - 21C Brimley towards Steeles via Scarborough Centre Stn'
 'South - 21C Brimley towards Kennedy Station via Scarborough Centre Stn'
 'North - 22 Coxwell towards Coxwell Station'
 'South - 22 Coxwell towards Queen' 'North - 23 Dawes towards St Clair'
 'South - 23 Dawes towards Main Street Station'
 'South - 23S Dawes Short Turn towards Victoria Park and St Clair'
 'North - 24A Victoria Park towards Steeles'
 'North - 24B Victoria Park towards Don Mills Station via Consumers Rd'
 'South - 24 Victoria Park towards Danforth'
 'South - 24 Victoria Park towards Victoria Park Station'
 'South - 24B Victoria Park towards Victoria Park Station via Consumers Rd'
 'North - 25A Don Mills towards Steeles via Don Valley Station and Don Mills Station'
 'North - 25B Don Mills towards Don Mills Station via Don Valley Station'
 'North - 25C Don Mills towards Steeles'
 'South - 25A Don Mills towards Broadview Station via Don Mills Station and Don Valley Station'
 'South - 25B Don Mills towards Broadview Station via Don Valley Station'
 'South - 25C Don Mills towards Don Mills Station'
 'South - 25S Don Mills Short Turn towards Don Valley Station'
 'East - 26 Dupont towards St George Station'
 'West - 26 Dupont towards Jane Station'
 'North - 27 Jane South towards Mount Dennis Station'
 'North - 27S Jane South Short Turn towards Eglinton'
 'South - 27 Jane South towards Jane Station'
 'East - 28 Bayview South towards Brick Works'
 'West - 28 Bayview South towards Davisville Station'
 'North - 29 Dufferin towards Wilson Station'
 'South - 29A Dufferin towards Exhibition (Dufferin Gate)'
 'North - 30 High Park North towards Runnymede'
 'South - 30 High Park North towards High Park Station'
 'East - 300A Bloor-Danforth towards Warden via Kipling Stn'
 'East - 300A Bloor-Danforth towards Warden'
 'East - 300B Bloor-Danforth towards Kennedy Station via Kipling Stn'
 'East - 300B Bloor-Danforth towards Kennedy Station'
 'East - 300S Bloor-Danforth Short Turn towards Victoria Park Stn'
 'West - 300A Bloor-Danforth towards Pearson Airport via Kipling Stn'
 'West - 300A Bloor-Danforth towards Pearson Airport'
 'West - 300B Bloor-Danforth towards West Mall'
 'West - 300S Bloor-Danforth Short Turn towards Castle Frank Stn'
 'West - 300S Bloor-Danforth Short Turn towards Keele Stn'
 'West - 300S Bloor-Danforth Short Turn towards Kipling Station'
 'East - 301 Queen Short Turn towards Roncesvalles'
 'East - 301 Queen towards Neville Park'
 'East - 301B Queen Replacement Bus towards Broadview Station'
 'West - 301 Queen  towards Long Branch'
 'West - 301 Queen Short Turn towards Roncesvalles'
 'West - 301B Queen Replacement Bus towards Parliament'
 'East - 304 King Short Turn towards Broadview and Queen'
 'East - 304 King towards Distillery'
 'East - 304A King towards Distillery'
 'West - 304 King towards Dundas West Station'
 'West - 304A King towards Distillery'
 'East - 305 Dundas Short Turn towards Broadview'
 'East - 305 Dundas towards Broadview Station'
 'West - 305 Dundas Short Turn towards Broadview'
 'West - 305 Dundas towards Dundas West Station'
 'East - 306 Carlton Short Turn towards Coxwell and Queen'
 'East - 306 Carlton towards Main Street Station'
 'East - 306B Carlton Replacement Bus towards Broadview & Gerrard'
 'West - 306 Carlton Short Turn towards Coxwell and Queen'
 'West - 306 Carlton towards High Park'
 'West - 306B Carlton Replacement Bus towards Spadina Station'
 'North - 307 Bathurst towards Steeles'
 'North - 307S Bathurst Short Turn towards Wilson'
 'South - 307 Bathurst towards Exhibition'
 'North - 31 Greenwood towards Greenwood Station'
 'South - 31 Greenwood towards Queen & Eastern'
 'North - 310 Spadina towards King'
 'North - 310 Spadina towards Spadina Station'
 'South - 310 Spadina towards King'
 'South - 310 Spadina towards Union Station'
 'East - 312 St Clair Short Turn'
 'East - 312 St Clair towards St Clair Station'
 'West - 312 St Clair Short Turn' 'West - 312 St Clair towards Keele'
 "East - 315 Evans-Brown's Line towards Royal York Station"
 "West - 315 Evans-Brown's Line towards Long Branch via Sherway"
 'North - 316 Kingston Rd-McCowan towards Steeles'
 'South - 316 Kingston Rd-McCowan towards Victoria Park and Kingston Rd'
 'East - 32 Eglinton West towards Mount Dennis Station'
 'West - 32 Eglinton West towards Renforth Station'
 'North - 320A Yonge towards Steeles'
 'North - 320B Yonge towards York Mills Station'
 'North - 320B Yonge towards York Mills/Wilson'
 'North - 320S Yonge Short Turn towards Eglinton Station'
 'South - 320 Yonge towards Queens Quay'
 'East - 322 Coxwell towards Victoria Park via Kingston Rd'
 'East - 322S Coxwell Short Turn towards Queen'
 'West - 322 Coxwell towards Broadview Station via Cosburn'
 'West - 322S Coxwell Short Turn towards Danforth'
 'North - 324 Victoria Park towards Steeles via Sheppard and Warden'
 'South - 324 Victoria Park towards Kingston Rd'
 'North - 325 Don Mills towards Steeles'
 'North - 325S Don Mills Short Turn towards Don Mills Station'
 'South - 325 Don Mills towards Commissioners'
 'South - 325S Don Mills Short Turn towards Eglinton'
 'North - 329 Dufferin towards Exhibition via Liberty Village'
 'North - 329 Dufferin towards Steeles via Liberty Village'
 'North - 329S Dufferin Short Turn towards Sheppard West Stn via Liberty Village'
 'North - 329S Dufferin Short Turn towards Wilson Station via Liberty Village'
 'South - 329 Dufferin towards Exhibition via Liberty Village'

In [816]:
# its weird that the shape_id column is an object column containing both string values and integer values
# lets look at the unique values in the shape_id column to understand why this is the case
print("Unique values in shape_id column of trips dataframe:")
print(trips["shape_id"].unique().tolist())

# it looks like shape_id either takes the format: string "shp-###-##" or integer ##### or string integer
# "#####"

# lets see if the same shape_id is represented as both an integer and a string in different records of trip

display(trips[(trips["shape_id"] == 1103634)].head(3))
display(trips[(trips["shape_id"] == "1103634")].head(3))

# lets standardize the shape_id column so that all values are strings to avoid redundancy in the trips table

trips["shape_id"] = trips["shape_id"].astype(str)

Unique values in shape_id column of trips dataframe:

,trip_id,route_id,service_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible
131072,133247081,4,2,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203384,1103634,1
131073,133247082,4,2,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203385,1103634,1
131074,133247083,4,2,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203386,1103634,1

,trip_id,route_id,service_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible
128813,133244822,4,1,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203380,1103634,1
128814,133244823,4,1,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203379,1103634,1
128815,133244824,4,1,Sheppard Line towards Sheppard-Yonge Station,NaN,1,2203382,1103634,1

In [817]:
# each dytype seems to be appropriate for the type of data in each column
# lets now look at the distribution of values for each column as well

# for the primary key, we will look at the number of unique values and their frequencies
# for integer columns we will look at the range and possibly mean
# for float values we will look at the range (float values usually will represent geographical coordinates so taking the mean/median doesnt make sense)
# for object/string values we will look at the unique values and their frequencies/mode

for col in trips.columns:
    if col == "trip_id":
        print(f"Distribution of {col} column in trips dataframe:")
        print(trips[col].value_counts(dropna=False))
        print("-" * 50)
    elif trips[col].dtype == "int64":
        print(f"Range of {col} column in trips dataframe: {trips[col].min()} to {trips[col].max()}")
        print("-" * 50)
        print(f"Distribution of {col} column in trips dataframe:")
        print(trips[col].value_counts(dropna=False))
        print("-" * 50)
    elif trips[col].dtype == "float64":
        print(f"Range of {col} column in trips dataframe: {trips[col].min()} to {trips[col].max()}")
        print("-" * 50)
    elif trips[col].dtype == "object":
        print(f"Distribution of {col} column in trips dataframe:")
        print(trips[col].value_counts(dropna=False))
        print("-" * 50)

Distribution of trip_id column in trips dataframe:
trip_id
106986020    1
80251020     1
11708020     1
126289070    1
117554020    1
            ..
18410080     1
86115070     1
39406010     1
10436080     1
133251420    1
Name: count, Length: 135412, dtype: int64
--------------------------------------------------
Range of route_id column in trips dataframe: 1 to 996
--------------------------------------------------
Distribution of route_id column in trips dataframe:
route_id
504    3246
63     2533
47     2393
1      2276
2      2206
       ...
406      16
405      14
400      14
403      12
830       2
Name: count, Length: 230, dtype: int64
--------------------------------------------------
Range of service_id column in trips dataframe: 1 to 7001
--------------------------------------------------
Distribution of service_id column in trips dataframe:
service_id
1       39810
2       33519
3       30298
5       29810
4        1929
4501       16
7001       16
4401       14
Name: count, dtype: int64
--------------------------------------------------
Distribution of trip_headsign column in trips dataframe:
trip_headsign
South - 63 Ossington towards Liberty Village                       1268
North - 47 Lansdowne towards Caledonia Station                     1199
North - 63A Ossington towards Cedarvale Station                    1195
South - 47 Lansdowne towards Queen                                 1194
Yonge-University Line towards Finch Station                        1145
                                                                   ...
West - 400 Lawrence Manor Community Bus  towards Caboto Terrace       1
West - 86C Scarborough towards Sheppard                               1
East - 400 Lawrence Manor Community Bus  towards Lawrence Plaza       1
South - 46S Martin Grove Short Turn towards The Westway               1
South - 329S Dufferin Short Turn towards Wilson Station               1
Name: count, Length: 800, dtype: int64
--------------------------------------------------
Distribution of trip_short_name column in trips dataframe:
trip_short_name
NaN    92831
A      21568
B      11275
C       4714
D       2915
S       1554
G        439
F        114
E          2
Name: count, dtype: int64
--------------------------------------------------
Range of direction_id column in trips dataframe: 0 to 1
--------------------------------------------------
Distribution of direction_id column in trips dataframe:
direction_id
0    68074
1    67338
Name: count, dtype: int64
--------------------------------------------------
Range of block_id column in trips dataframe: 70220 to 99622222
--------------------------------------------------
Distribution of block_id column in trips dataframe:
block_id
470220      332
770110      328
920110      306
226310      300
330110      300
           ...
95410102      2
5427272       2
5088451       2
5228281       1
9890991       1
Name: count, Length: 3861, dtype: int64
--------------------------------------------------
Distribution of shape_id column in trips dataframe:
shape_id
1103634       882
1103632       870
shp-36-84     839
shp-36-35     819
shp-84-19     686
             ...
shp-167-51      1
shp-165-51      1
shp-162-53      1
shp-161-02      1
1103577         1
Name: count, Length: 1542, dtype: int64
--------------------------------------------------
Range of wheelchair_accessible column in trips dataframe: 1 to 2
--------------------------------------------------
Distribution of wheelchair_accessible column in trips dataframe:
wheelchair_accessible
1    119062
2     16350
Name: count, dtype: int64
--------------------------------------------------

In [818]:
# There are some obervations we can make from this

# 1) There are 135412 unique rows in the trips dataframe; each row seems to correspnd to a unique value of trip_id (135412 unique trip_ids)
#    This is a good sign that the primary key is unique

# 2) The route_id column contains 230 unique values ranging from 1 to 996. This matches the number of unique route_ids in the routes
#    dataframe and the range of route_id's in the routes dataframe. This means all routes will have one or more trips scheduled, which is a good
#    sign that the feed is complete

# 3) it seems that all scheduled trips will follow 8 possible weekly schedules (service_id's). 

# 4) it seems many trips share the same trip_headsign (ranging from 1 to thousands sharing the same headsign), this makes sense since
#    many trips from different routes, scheduled at different times, can share the same destination and therefore the same headsign

# 5) Most trips do not have a specified trip_short_name (value NaN) but the rest seem to have an arbritary letter assigned as a trip_short_name
#    There doesnt seem to be much documentation of what exactly the trip_short_name represents in the TTC feed, but they seem to refer to the
#.   letter associated with a bus trip in the TTC system i.e. the 102 "D" (see below)

# 6) The range of direction_id is from 0 to 1 which makes sense since direction_id entails the direction of travel of the trip 
#    (0 vs 1 meaning eastbound vs westbound, etc.)

# 7) block_id represents the block of sequential trips made by the same vehicle, so it makes sense that there are fewer unique blocks than trips.
#    it is suprising that hundreds of trips share the same block_id, but this could just be looped routes or the same sequence of routes being 
#    travelled through by different veichles at different schedules

# 8) its weird that there are different id formats in the shape_id column, but as long as the ids are consistent and unique and correspond to the
#    same id's in the shapes dataframe, then it shouldnt be much of an issue for analysis

# 9) it seems that the TTC completely specifies wheel chair accesibility for each trip (value 1 or 2)

In [819]:
# what is the range of route_id values in the routes dataframe
print("Range of route_id values in routes dataframe:")
print(routes["route_id"].min(), "to", routes["route_id"].max())
print("-" * 50)

# print out records with a trip_short_name of "D" 
print("Trips with trip_short_name 'D':")
print(trips[trips["trip_short_name"] == "D"].head(10).to_string())
print("-" * 50)

Range of route_id values in routes dataframe:
1 to 996
--------------------------------------------------
Trips with trip_short_name 'D':
       trip_id  route_id  service_id                                    trip_headsign trip_short_name  direction_id  block_id    shape_id  wheelchair_accessible
2005  74998070       102           2  North - 102D Markham Rd towards Major Mackenzie               D             1  10222220  shp-102-08                      1
2006  23309020       102           1  North - 102D Markham Rd towards Major Mackenzie               D             1   1020990  shp-102-08                      1
2007  71179080       102           5  North - 102D Markham Rd towards Major Mackenzie               D             1  10214140  shp-102-08                      1
2008  23577070       102           2  North - 102D Markham Rd towards Major Mackenzie               D             1  10214140  shp-102-08                      1
2009  75263020       102           1  North - 102D Markham Rd towards Major Mackenzie               D             1  10223231  shp-102-08                      1
2010  17075010       102           3  North - 102D Markham Rd towards Major Mackenzie               D             1  10236150  shp-102-08                      1
2011  79484070       102           2  North - 102D Markham Rd towards Major Mackenzie               D             1  10217170  shp-102-08                      1
2012  22651010       102           3  North - 102D Markham Rd towards Major Mackenzie               D             1   1020440  shp-102-08                      1
2013  76440020       102           1  North - 102D Markham Rd towards Major Mackenzie               D             1   1020990  shp-102-08                      1
2014  27679020       102           1  North - 102D Markham Rd towards Major Mackenzie               D             1   1020330  shp-102-08                      1
--------------------------------------------------

In [820]:
# lets look at the presence of null values and empty strings in the rows of the trips dataframe

print("Number of null values in each column of trips dataframe:")
print(trips.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of trips dataframe:")
object_columns = trips.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (trips[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

Number of null values in each column of trips dataframe:
trip_id                      0
route_id                     0
service_id                   0
trip_headsign                0
trip_short_name          92831
direction_id                 0
block_id                     0
shape_id                     0
wheelchair_accessible        0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of trips dataframe:
trip_headsign: 0
trip_short_name: 0
shape_id: 0
--------------------------------------------------

In [821]:
# so it seems like there are missing values in the trip_short_name column

# lets reprint the count of unique values in the trip_short_name column
print("Distribution of trip_short_name column in trips dataframe:")
print(trips["trip_short_name"].value_counts(dropna=False))
print("-" * 50)

# This is most likely due to some veichles not needing a letter designation for the trip name (i.e. it may be bus 100 not bus 100 "A")

# print out some records with NaN trip_short_name values and some records with A trip_short_name values to compare
print("Trips with NaN trip_short_name:")
display(trips[trips["trip_short_name"].isna()].head(3))

print("Trips with trip_short_name 'A':")
display(trips[trips["trip_short_name"] == "A"].head(3))

# so it seems that the initial hypothesis was true, instead of leaving the trip_short_name blank for trips that dont have a letter designation.
# lets fill the NaN values in the trip_short_name column with "No Designation" to make it more clear that these trips do not have a short name designation instead of leaving it as blank/NaN

trips["trip_short_name"] = trips["trip_short_name"].fillna("No Designation")

print("-" * 50)
print("Updated distribution of trip_short_name column in trips dataframe:")
print(trips["trip_short_name"].value_counts(dropna=False))
print("-" * 50)

Distribution of trip_short_name column in trips dataframe:
trip_short_name
NaN    92831
A      21568
B      11275
C       4714
D       2915
S       1554
G        439
F        114
E          2
Name: count, dtype: int64
--------------------------------------------------
Trips with NaN trip_short_name:

,trip_id,route_id,service_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible
0,106986020,10,1,East - 10 Van Horne towards Victoria Park,NaN,0,100112,shp-10-03,1
1,118048020,10,1,East - 10 Van Horne towards Victoria Park,NaN,0,100111,shp-10-03,1
2,102340020,10,1,East - 10 Van Horne towards Victoria Park,NaN,0,100112,shp-10-03,1

Trips with trip_short_name 'A':

,trip_id,route_id,service_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible
42,1093010,100,3,North - 100A Flemingdon Park towards Don Valle...,A,1,1000880,shp-100-02,1
43,111645010,100,3,North - 100A Flemingdon Park towards Don Valle...,A,1,1000550,shp-100-02,1
44,109437070,100,2,North - 100A Flemingdon Park towards Don Valle...,A,1,1000440,shp-100-02,1

--------------------------------------------------
Updated distribution of trip_short_name column in trips dataframe:
trip_short_name
No Designation    92831
A                 21568
B                 11275
C                  4714
D                  2915
S                  1554
G                   439
F                   114
E                     2
Name: count, dtype: int64
--------------------------------------------------

In [822]:
# lets now re-look at the presence of null values and empty strings in the rows of the trips dataframe

print("Number of null values in each column of trips dataframe:")
print(trips.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of trips dataframe:")
object_columns = trips.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (trips[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

# overall, looks like the feed for stops has complete data

Number of null values in each column of trips dataframe:
trip_id                  0
route_id                 0
service_id               0
trip_headsign            0
trip_short_name          0
direction_id             0
block_id                 0
shape_id                 0
wheelchair_accessible    0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of trips dataframe:
trip_headsign: 0
trip_short_name: 0
shape_id: 0
--------------------------------------------------

#### Stop_times.txt

In [823]:
# print data types of stop_times dataframe

print("Data types of stop_times dataframe:")
print(stop_times.dtypes)
print("-" * 50)

Data types of stop_times dataframe:
trip_id                  int64
arrival_time            object
departure_time          object
stop_id                  int64
stop_sequence            int64
stop_headsign           object
pickup_type              int64
drop_off_type            int64
shape_dist_traveled    float64
timepoint              float64
dtype: object
--------------------------------------------------

In [824]:
# lets first identify columns that are not used in the feed and drop them from the dataframe to simplify our analysis
# we can identify these columns by looking at the unique values in each column and seeing if they are all NaN or empty strings

for col in stop_times.columns:
    unique_values = stop_times[col].unique()
    print(f"Unique values in {col} column of stop_times dataframe:")
    print(unique_values)
    print("-" * 50)

Unique values in trip_id column of stop_times dataframe:
[ 10000080 100001020 100002020 ... 133250515 133250516 133250424]
--------------------------------------------------
Unique values in arrival_time column of stop_times dataframe:
['20:25:53' '20:27:14' '20:29:21' ... '04:40:02' '28:47:21' '28:55:41']
--------------------------------------------------
Unique values in departure_time column of stop_times dataframe:
['20:25:53' '20:27:14' '20:29:21' ... '04:40:02' '28:47:21' '28:55:41']
--------------------------------------------------
Unique values in stop_id column of stop_times dataframe:
[ 4386 38709 42823 ... 13750 13751 13754]
--------------------------------------------------
Unique values in stop_sequence column of stop_times dataframe:
[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
   1  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132]
--------------------------------------------------
Unique values in stop_headsign column of stop_times dataframe:
['31 GREENWOOD TO GREENWOOD STATION'
 '161 ROGERS RD TO MOUNT DENNIS STATION' '91 WOODBINE TO LAWRENCE'
 '510A SPADINA UNION STN' '22 COXWELL COXWELL STATION'
 '45A KIPLING STEELES' '28 BAYVIEW SOUTH BRICK WORKS'
 '44 KIPLING SOUTH KIPLING STN' '154 CURRAN HALL TO KENNEDY STATION'
 '53 STEELES EAST FINCH STN' '12B KINGSTON RD KENNEDY STN via BRIMLEY'
 '48 RATHBURN ROYAL YORK STN' '365 PARLIAMENT BLUE NIGHT CASTLE FRANK STN'
 '935 JANE EXPRESS TO PIONEER VILLAGE STATION' '511 BATHURST EXHIBITION'
 '22 COXWELL QUEEN' '113 DANFORTH MAIN STREET STN'
 '7 BATHURST BATHURST STN' '63A OSSINGTON TO CEDARVALE STATION'
 '11C BAYVIEW TO SUNNYBROOK'
 '129A McCOWAN NORTH TO MAJOR MACKENZIE via SCARBOROUGH CENTRE STN'
 '102B MARKHAM RD STEELES' '72C PAPE TO COMMISSIONERS via PAPE STATION'
 '52G LAWRENCE WEST MARTIN GROVE via THE WESTWAY'
 '506 CARLTON MAIN STREET STN'
 '123B SHERWAY TO LONG BRANCH via SHORNCLIFFE and EAST MALL'
 '501 QUEEN HUMBER' '105 DUFFERIN NORTH TO SHEPPARD WEST STATION'
 '160 BATHURST NORTH CENTRE STREET'
 '123D SHERWAY TO SHERWAY GARDENS via SHORNCLIFFE and EAST MALL'
 '60A STEELES WEST' '47 LANSDOWNE TO CALEDONIA STATION'
 '36 FINCH WEST TO FINCH WEST STATION'
 '149 ETOBICOKE-BLOOR TO JANE STATION'
 '503 KINGSTON RD TO VICTORIA PARK via PARLIAMENT and QUEEN'
 '80A QUEENSWAY TO KEELE STATION'
 '29A DUFFERIN TO EXHIBITION (DUFFERIN GATE)'
 '63 OSSINGTON TO LIBERTY VILLAGE'
 '54 LAWRENCE EAST TO DON VALLEY STATION'
 '85B SHEPPARD EAST TO MEADOWVALE' '74 MOUNT PLEASANT TO EGLINTON STATION'
 '29 DUFFERIN WILSON STATION' '76A ROYAL YORK SOUTH LAKE SHORE'
 '114 QUEENS QUAY EAST TO UNION STATION'
 '900 AIRPORT EXPRESS TO PEARSON AIRPORT'
 '73B ROYAL YORK TO MOUNT DENNIS STATION' '512 ST CLAIR KEELE'
 '505 DUNDAS TO DUNDAS WEST STATION'
 '25A DON MILLS TO BROADVIEW STATION via DON MILLS STATION and DON VALLEY STATION'
 '945 KIPLING EXPRESS TO STEELES'
 '25B DON MILLS TO BROADVIEW STATION via DON VALLEY STATION'
 '107 ALNESS CHESSWOOD TO FINCH WEST STATION'
 '86A SCARBOROUGH TORONTO ZOO' '77 SWANSEA QUEENSWAY'
 '995 YORK MILLS EXPRESS TO U of T SCARBOROUGH' '503 KINGSTON RD TO YORK'
 '118 THISTLE DOWN THISTLE DOWN via TANDRIDGE' '16 McCOWAN WARDEN STN'
 '92 WOODBINE SOUTH WOODBINE STN'
 '203 HIGH PARK TO HIGH PARK via WEST ROAD' '151 LESLIE NORTH TO STEELES'
 '94A WELLESLEY OSSINGTON STN' '161 ROGERS RD OSSINGTON STN'
 '154 CURRAN HALL TO U of T SCARBOROUGH' '47 LANSDOWNE TO QUEEN'
 '512 ST CLAIR ST CLAIR STATION'
 '110A ISLINGTON SOUTH ISLINGTON STN via BROWNS LINE and HORNER'
 '67A PHARMACY ELLESMERE' '75 SHERBOURNE TO SHERBOURNE STATION'
 '30 HIGH PARK NORTH TO RUNNYMEDE'
 '133 NEILSON TO MORNINGSIDE HEIGHTS via SCARBOROUGH CENTRE STN'
 '52 LAWRENCE WEST TO LAWRENCE STATION' '26 DUPONT TO JANE STATION'
 'NOT IN SERVICE' '935 JANE EXPRESS TO JANE STATION'
 '12A KINGSTON RD VICTORIA PARK STN via BRIMLEY and VARIETY VILLAGE'
 '79A SCARLETT RD LAWRENCE & JANE via PRITCHARD/FOXWELL'
 '71 RUNNYMEDE TO INDUSTRY ST via MOUNT DENNIS STATION'
 '395 YORK MILLS BLUE NIGHT YORK MILLS STN'
 '52G LAWRENCE WEST LAWRENCE WEST STN' '50 BURNHAMTHORPE ISLINGTON STN'
 '60 STEELES WEST FINCH STN via PIONEER VILLAGE STN'
 "70 O'CONNOR TO EGLINTON" '116 MORNINGSIDE FINCH and MORNINGSIDE'
 '203 HIGH PARK TO HIGH PARK STATION via COLBORNE LODGE DRIVE'
 '69 WARDEN SOUTH TO WARDEN STATION'
 '21C BRIMLEY TO STEELES via SCARBOROUGH CENTRE STN'
 '135 GERRARD WARDEN STN' '130A MIDDLEFIELD TO SCARBOROUGH CENTRE STN'
 '35B JANE TO MOUNT DENNIS STATION via HULLMAR'
 '114 QUEENS QUAY EAST TO CARLAW via OOKWEMIN MINISING'
 '68 WARDEN WARDEN STN' '506 CARLTON HIGH PARK' '23 DAWES ST CLAIR'
 '191 UNDERHILL TO YORK MILLS' '511 BATHURST BATHURST STN' '64 MAIN QUEEN'
 '307 BATHURST BLUE NIGHT STEELES' '113 DANFORTH KENNEDY STN'
 '185 SHEPPARD CENTRAL TO DON MILLS STATION'
 '26 DUPONT TO ST GEORGE STATION' '24 VICTORIA PARK VICTORIA PARK STN'
 '100A FLEMINGDON PARK TO BROADVIEW STATION'
 '158 TRETHEWEY TO WESTON RD & OAK' '39A FINCH EAST NEILSON'
 '32 EGLINTON WEST TO RENFORTH STATION' '37 ISLINGTON ISLINGTON STN'
 '42 CUMMER TO MIDDLEFIELD (DYNAMIC)' '84A SHEPPARD WEST WESTON RD'
 '89 WESTON TO ALBION RD via MOUNT DENNIS STATION'
 '900 AIRPORT EXPRESS TO KIPLING STATION' '501 QUEEN LONG BRANCH'
 '49 BLOOR WEST MARKLAND WOOD' '986 SCARBOROUGH EXPRESS TO SHEPPARD'
 '131 NUGGET TO OLD FINCH & MORNINGVIEW via SCARBOROUGH CENTRE STN'
 '25C DON MILLS TO DON MILLS STATION'
 '52A LAWRENCE WEST PEARSON AIRPORT via DIXON RD' '104 FAYWOOD WILSON STN'
 '46 MARTIN GROVE STEELES' '149 ETOBICOKE-BLOOR TO KIPLING STATION'
 '110C ISLINGTON SOUTH KIPLING and LAKE SHORE'
 '927B HIGHWAY 27 EXPRESS TO STEELES via HUMBER COLLEGE STATION'
 '108B DRIFTWOOD PIONEER VILLAGE STN via ARLETA'
 '98 WILLOWDALE-SENLAC STEELES via SHEPPARD-YONGE STN'
 '83 JONES COMMISSIONERS' '102C MARKHAM RD STEELES via DYNAMIC DR'
 '507 LONG BRANCH TO LONG BRANCH' '39 FINCH EAST FINCH STN'
 '98 WILLOWDALE-SENLAC PECKHAM via SHEPPARD-YONGE STN'
 '94B WELLESLEY WELLESLEY STN' '95 YORK MILLS YORK MILLS STN'
 '189 STOCKYARDS SCARLETT RD' '165 WESTON RD NORTH STEELES'
 '509 HARBOURFRONT UNION STN' '353 STEELES BLUE NIGHT YORK UNIVERSITY'
 '121 ESPLANADE-RIVER UNION STN' '36 FINCH WEST TO FINCH STATION'
 '82 ROSEDALE SUMMERHILL' '57 MIDLAND STEELES'
 '84 SHEPPARD WEST SHEPPARD-YONGE STN via SHEPPARD WEST STN'
 '904 SHEPPARD-KENNEDY EXPRESS TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '135 GERRARD MAIN STREET STN'
 '119B TORBARRIE TO WILSON STATION via TORBARRIE'
 '32 EGLINTON WEST TO MOUNT DENNIS STATION'
 '506B CARLTON TO BROADVIEW and GERRARD'
 '79B SCARLETT RD LAWRENCE & JANE via ST CLAIR' '501 QUEEN NEVILLE PARK'
 '53B STEELES EAST TO MORNINGSIDE'
 '121 ESPLANADE-RIVER TO HENNICK BRIDGEPOINT HOSPITAL'
 '386 SCARBOROUGH BLUE NIGHT TO KENNEDY STATION'
 '116 MORNINGSIDE KENNEDY STN' '77 SWANSEA RUNNYMEDE STN'
 '64 MAIN MAIN STREET STN'
 '300A BLOOR-DANFORTH BLUE NIGHT PEARSON AIRPORT'
 '131S NUGGET SHORT TURN TO MORNINGSIDE' '97C YONGE TO EGLINTON STATION'
 '52D LAWRENCE WEST McNAUGHTON via DIXON RD'
 '96A WILSON CARRIER DR via KIPLING and JOHN GARLAND'
 '906 AIRPORT-HUMBER COLLEGE EXPRESS TO HUMBERWOOD via HUMBER COLLEGE STATION'
 '60 STEELES WEST FINCH STN' '509 HARBOURFRONT TO EXHIBITION'
 '37 ISLINGTON TO ISLINGTON STATION via WOODBINE RACETRACK and REXDALE'
 '133 NEILSON TO MORNINGSIDE HEIGHTS via SCARBOROUGH CENTRE STN and CENTENARY HOSPITAL'
 '927D HIGHWAY 27 EXPRESS TO STEELES & SIGNAL HILL via HUMBER COLLEGE STATION'
 '115 SILVER HILLS LESLIE' '109B RANEE NEPTUNE via FLEMINGTON'
 '927B HIGHWAY 27 EXPRESS TO KIPLING STATION via HUMBER COLLEGE STATION'
 '86C SCARBOROUGH SHEPPARD' '304 KING BLUE NIGHT DUNDAS WEST STN'
 '62 MORTIMER TO MAIN STREET STATION via BROADVIEW STATION'
 '17 BIRCHMOUNT WARDEN STN' '78 ST ANDREWS BAYVIEW'
 '168 SYMINGTON TO MOUNT DENNIS STATION' '45 KIPLING KIPLING STN'
 '952 LAWRENCE WEST EXPRESS TO LAWRENCE STATION'
 '44 KIPLING SOUTH LAKE SHORE'
 '119B TORBARRIE TO MILVAN via TORBARRIE and FENMAR' '504 KING SHORT TURN'
 '97A YONGE TO ST CLAIR STATION' '124 SUNNYBROOK TO SUNNYBROOK HOSPITAL'
 '929 DUFFERIN EXPRESS TO WILSON STN' '20 CLIFFSIDE TO KENNEDY STATION'
 '902 MARKHAM RD EXPRESS TO WARDEN STATION via CENTENNIAL COLLEGE'
 '85C SHEPPARD EAST TO TORONTO ZOO via MEADOWVALE'
 '905B EGLINTON EAST EXPRESS TO U of T SCARBOROUGH'
 '925 DON MILLS EXPRESS TO BROADVIEW STATION via DON MILLS STATION and DON VALLEY STATION'
 '927D HIGHWAY 27 EXPRESS TO KIPLING STATION via HUMBER COLLEGE STATION'
 '103 MOUNT PLEASANT NORTH TO DONCLIFFE'
 '96S WILSON SHORT TURN TO HUMBER COLLEGE STATION'
 '65 PARLIAMENT CASTLE FRANK STN' '504D KING TO BROADVIEW STATION'
 '40A JUNCTION-DUNDAS WEST KIPLING STN'
 '16 McCOWAN TO SCARBOROUGH CENTRE STN' '109C RANEE NEPTUNE via VARNA'
 '905A EGLINTON EAST EXPRESS TO CONLINS'
 '40B JUNCTION-DUNDAS WEST JANE AND ST CLAIR'
 '106 SENTINEL SHEPPARD WEST STN' '168 SYMINGTON DUNDAS WEST STN'
 '109B RANEE TO CEDARVALE STATION via FLEMINGTON'
 '90 VAUGHAN TO ST CLAIR WEST STATION' 'LINE 5 SHUTTLE BUS WESTBOUND'
 '510B SPADINA TO QUEENS QUAY' '927 HIGHWAY 27 EXPRESS TO KIPLING STATION'
 '905B EGLINTON EAST EXPRESS TO KENNEDY STATION' '511 BATHURST KING'
 '103 MOUNT PLEASANT NORTH TO EGLINTON STATION'
 '109C RANEE TO CEDARVALE STATION via VARNA' '126 CHRISTIE CHRISTIE STN'
 '80 QUEENSWAY TO SHERWAY GARDENS' '66 PRINCE EDWARD OLD MILL STN'
 '61 AVENUE RD NORTH EGLINTON STN' '95B YORK MILLS U of T SCARBOROUGH'
 '506B CARLTON TO SPADINA STATION'
 '89 WESTON TO KEELE STATION via MOUNT DENNIS STATION'
 '122 GRAYDON HALL ROYWOOD via LESMILL'
 '34 EGLINTON TO MOUNT DENNIS STATION' '504D KING TO PARLIAMENT'
 '100A FLEMINGDON PARK TO DON VALLEY STATION'
 '35B JANE TO PIONEER VILLAGE STN via HULLMAR'
 '76B ROYAL YORK SOUTH QUEENSWAY and GRAND AVENUE'
 '90 VAUGHAN TO CEDARVALE STATION' '156 MILLWOOD TO THORNCLIFFE PARK'
 '93 PARKVIEW HILLS WOODBINE STN' '35A JANE TO MOUNT DENNIS STATION'
 '108A DRIFTWOOD SHEPPARD WEST STN via GRANDRAVINE'
 '57 MIDLAND KENNEDY STN' '20 CLIFFSIDE MAIN STREET STN'
 '123B SHERWAY TO KIPLING STN via EAST MALL and SHORNCLIFFE'
 '125 DREWRY BATHURST (TORRESDALE)' '66B PRINCE EDWARD LAKE SHORE'
 '166S TORYORK SHORT TURN TO EMERY STATION'
 '335S JANE BLUE NIGHT SHORT TURN TO PIONEER VILLAGE STATION'
 "8 BROADVIEW TO WARDEN STATION via BROADVIEW STATION & O'CONNOR"
 '158 TRETHEWEY TO KEELESDALE STATION' "70 O'CONNOR TO COXWELL STATION"
 '300A BLOOR-DANFORTH BLUE NIGHT WARDEN' '126 CHRISTIE ST CLAIR WEST STN'
 '50 BURNHAMTHORPE MILL ROAD' '76 ROYAL YORK SOUTH ROYAL YORK STN'
 '101 DOWNSVIEW PARK TO FINCH WEST STATION via DOWNSVIEW PARK STATION'
 '65 PARLIAMENT TO QUEENS QUAY & SHERBOURNE'
 '73C ROYAL YORK CLAIREPORT via ALBION RD' '132 MILNER McLEVIN & HUPFIELD'
 '73 ROYAL YORK TO ROYAL YORK STATION' '11 BAYVIEW TO DAVISVILLE STN'
 '15 EVANS ROYAL YORK STN'
 '108A DRIFTWOOD PIONEER VILLAGE STN via GRANDRAVINE'
 '339S FINCH EAST BLUE NIGHT SHORT TURN TO TAPSCOTT'
 '24A VICTORIA PARK STEELES' '102 MARKHAM RD WARDEN STN'
 '19 BAY TO DUPONT'
 '960 STEELES WEST EXPRESS TO FINCH STATION via PIONEER VILLAGE STATION'
 '505 DUNDAS TO BROADVIEW STATION' '9 BELLAMY TO SCARBOROUGH CENTRE STN'
 '939B FINCH EXPRESS TO FINCH WEST STATION via SCARBOROUGH CENTRE STN and FINCH STATION'
 '62 MORTIMER TO HENNICK BRIDGEPOINT HOSPITAL via BROADVIEW STATION'
 '39 FINCH EAST TO YONGE STREET'
 '41 KEELE TO KEELE STATION via KEELESDALE STATION' '68A WARDEN STEELES'
 '306 CARLTON BLUE NIGHT MAIN STREET STN'
 '96S WILSON SHORT TURN TO HUMBER COLLEGE STATION via KIPLING AND JOHN GARLAND'
 '115 SILVER HILLS YORK MILLS STN' '99 ARROW RD'
 '87A COSBURN TO MAIN STREET STATION via EAST YORK ACRES'
 '300B BLOOR-DANFORTH BLUE NIGHT KENNEDY STN'
 '945 KIPLING EXPRESS TO KIPLING STN'
 '108B DRIFTWOOD SHEPPARD WEST STN via ARLETA'
 '160 BATHURST NORTH WILSON STN'
 '960D STEELES WEST EXPRESS TO HIGHWAY 27 via PIONEER VILLAGE STATION'
 '165 WESTON RD NORTH YORK MILLS STN' '106 SENTINEL PIONEER VILLAGE STN'
 '54A LAWRENCE EAST TO STARSPRAY'
 '87A COSBURN TO BROADVIEW STATION via EAST YORK ACRES'
 '94 WELLESLEY CASTLE FRANK STN' '19 BAY TO UNION STATION'
 '902 MARKHAM RD EXPRESS TO STEELES AVENUE EAST via CENTENNIAL COLLEGE'
 '11 BAYVIEW TO DAVISVILLE STN via SUNNYBROOK' '7 BATHURST STEELES'
 '324 VICTORIA PARK BLUE NIGHT KINGSTON RD'
 '87C COSBURN TO BROADVIEW STATION' '86 SCARBOROUGH KENNEDY STN'
 '906 AIRPORT-HUMBER COLLEGE EXPRESS TO PEARSON AIRPORT (VISCOUNT STATION)'
 '117 BIRCHMOUNT SOUTH TO WARDEN STATION'
 '87C COSBURN TO MAIN STREET STATION' '17C BIRCHMOUNT STEELES and WARDEN'
 '27 JANE SOUTH TO MOUNT DENNIS STATION'
 "8 BROADVIEW TO HENNICK BRIDGEPOINT HOSPITAL via O'CONNOR & BROADVIEW STATION"
 '925 DON MILLS EXPRESS TO STEELES via DON VALLEY STATION and DON MILLS STATION'
 '111 EAST MALL KIPLING STN' '112 WEST MALL KIPLING STN'
 '72 PAPE TO DON VALLEY STATION via PAPE STATION'
 '123C SHERWAY TO KIPLING STN via NORTH QUEEN and SHORNCLIFFE'
 '18A CALEDONIA TO CALEDONIA STATION via BRIDGELAND'
 '40 JUNCTION-DUNDAS WEST DUNDAS WEST STN'
 '127 DAVENPORT ST CLAIR & OLD WESTON RD'
 '339 FINCH EAST BLUE NIGHT FINCH STN'
 '334A EGLINTON BLUE NIGHT TO PEARSON AIRPORT'
 '23 DAWES TO MAIN STREET STATION'
 '39B FINCH EAST OLD FINCH and MORNINGVIEW'
 '339 FINCH EAST BLUE NIGHT MARKHAM RD'
 '164 CASTLEFIELD TO CEDARVALE STATION' '92 WOODBINE SOUTH LAKE SHORE'
 '903A KENNEDY STN-SCARB EXPRESS TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '112C WEST MALL DISCO RD via RENFORTH STN'
 '301B QUEEN BLUE NIGHT TO PARLIAMENT' '510 SPADINA TO SPADINA STN'
 '75 SHERBOURNE TO QUEENS QUAY via SOUTH DRIVE'
 '98S WILLOWDALE-SENLAC SHORT TURN' '122 GRAYDON HALL YORK MILLS STN'
 '96B WILSON HUMBERLINE / ALBION via WESTHUMBER and MARTIN GROVE'
 '30 HIGH PARK NORTH TO HIGH PARK STATION'
 '69 WARDEN SOUTH TO ST CLAIR (BARKDENE HILLS)'
 '51 LESLIE TO DONLANDS STATION via LAIRD STATION'
 '127 DAVENPORT SPADINA STN' '35A JANE TO PIONEER VILLAGE STN'
 '336S FINCH WEST BLUE NIGHT SHORT TURN TO FINCH WEST STATION'
 '41 KEELE TO PIONEER VILLAGE STN via KEELESDALE STATION'
 '48 RATHBURN MILL RD'
 '131 NUGGET TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '43A KENNEDY STEELES' '13 AVENUE RD EGLINTON STN'
 '903B KENNEDY STN-SCARB EXPRESS TO SCARBOROUGH CENTRE STN'
 '354 LAWRENCE EAST BLUE NIGHT TO STARSPRAY'
 '85A SHEPPARD EAST TO ROUGE HILL GO STN' '9 BELLAMY WARDEN STN'
 '102C MARKHAM RD WARDEN STN via DYNAMIC DR'
 '340 JUNCTION BLUE NIGHT TO ST CLAIR & GUNNS'
 '85 SHEPPARD EAST TO DON MILLS STN'
 '38 HIGHLAND CREEK TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '184 ANCASTER PARK TO WILSON STATION' '14 GLENCAIRN DAVISVILLE STN'
 '110C ISLINGTON SOUTH ISLINGTON STN' '104 FAYWOOD SHEPPARD WEST STN'
 '55 WARREN PARK TO JANE STATION' '67 PHARMACY VICTORIA PARK STN'
 '15 EVANS TO SHERWAY GARDENS' '86D SCARBOROUGH BEECHGROVE via LAWRENCE'
 '164 CASTLEFIELD TO MOUNT DENNIS STATION' '27 JANE SOUTH TO JANE STATION'
 '129B McCOWAN NORTH TO STEELES via SCARBOROUGH CENTRE STN'
 '53A STEELES EAST STAINES' '95A YORK MILLS'
 '929 DUFFERIN EXPRESS EXHIBITION (DUFFERIN GATE)'
 '120 CALVINGTON TO SHEPPARD & JANE'
 '960B STEELES WEST EXPRESS TO MARTIN GROVE via PIONEER VILLAGE STATION'
 '118 THISTLE DOWN THISTLE DOWN' '11A BAYVIEW TO STEELES via SUNNYBROOK'
 '96S WILSON SHORT TURN TO HUMBER COLLEGE STATION via WESTHUMBER AND MARTIN GROVE'
 '501 QUEEN RONCESVALLES'
 '59 MAPLE LEAF LAWRENCE WEST STN via CULFORD/BENTON'
 '151 LESLIE NORTH TO LESLIE STATION'
 '162 LAWRENCE-DONWAY TO DON VALLEY STATION'
 '927C HIGHWAY 27 EXPRESS TO KIPLING STATION via ATTWELL'
 '130A MIDDLEFIELD STEELES' '34 EGLINTON TO KENNEDY STATION'
 '101A DOWNSVIEW PARK TO STANLEY GREENE via DOWNSVIEW PARK STATION'
 '83 JONES DONLANDS STN' '99 ARROW RD JANE'
 '37A ISLINGTON TO HUMBER COLLEGE via REXDALE and WOODBINE RACETRACK'
 '343 KENNEDY BLUE NIGHT KENNEDY STN'
 '88B SOUTH LEASIDE TO WICKSTEED via LAIRD STATION'
 '507 LONG BRANCH TO HUMBER'
 '385 SHEPPARD EAST BLUE NIGHT ROUGE HILL GO STATION'
 '43 KENNEDY KENNEDY STN'
 '320S YONGE BLUE NIGHT SHORT TURN TO FINCH STATION'
 '129 McCOWAN NORTH TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '107 ALNESS CHESSWOOD TO SHEPPARD WEST STATION'
 '71 RUNNYMEDE TO RUNNYMEDE STATION via MOUNT DENNIS STATION'
 '117 BIRCHMOUNT SOUTH TO VICTORIA PARK STATION'
 '38A HIGHLAND CREEK TO ROUGE HILL GO STN via SCARBOROUGH CENTRE STN'
 '73 ROYAL YORK ROYAL YORK STN' '88A SOUTH LEASIDE TO THORNCLIFFE PARK'
 '927D HIGHWAY 27 EXPRESS TO KIPLING STATION via ROYALCREST & HUMBER COLLEGE STATION'
 '82 ROSEDALE ROSEDALE STN' '74 MOUNT PLEASANT TO ST CLAIR STATION'
 '105 DUFFERIN NORTH TO STEELES' '72S PAPE SHORT TURN TO EGLINTON'
 '51B LESLIE TO DON MILLS via LAIRD STATION' '37B ISLINGTON TO STEELES'
 '31 GREENWOOD TO QUEEN & EASTERN'
 '59A MAPLE LEAF LAWRENCE WEST STN via CULFORD/BENTON'
 '112B WEST MALL RENFORTH STN' '944 KIPLING SOUTH EXPRESS KIPLING STN'
 '25A DON MILLS TO STEELES via DON VALLEY STATION and DON MILLS STATION'
 '102A MARKHAM RD PROGRESS/ CENTENNIAL COLLEGE'
 '904 SHEPPARD-KENNEDY EXPRESS TO DON MILLS STATION via SCARBOROUGH CENTRE STN'
 '396 WILSON BLUE NIGHT MARTIN GROVE and STEELES'
 '96B WILSON YORK MILLS STN via MARTIN GROVE and WESTHUMBER'
 '939B FINCH EXPRESS TO KENNEDY STATION via FINCH STATION and SCARBOROUGH CENTRE STN'
 '100B FLEMINGDON PARK TO BROADVIEW STATION via LINKWOOD'
 '320B YONGE BLUE NIGHT TO YORK MILLS/WILSON'
 '191 UNDERHILL TO DON VALLEY STATION' '97A YONGE TO STEELES'
 '96A WILSON YORK MILLS STN via JOHN GARLAND and KIPLING'
 '133 NEILSON TO KENNEDY STATION via CENTENARY HOSPITAL and SCARBOROUGH CENTRE STN'
 '944 KIPLING SOUTH EXPRESS LAKE SHORE' '42 CUMMER TO FINCH STATION'
 '995 YORK MILLS EXPRESS TO YORK MILLS STN'
 '169A HUNTINGWOOD DON MILLS STN via VAN HORNE'
 '59B MAPLE LEAF WESTON RD via BENTON/CULFORD and CHURCH'
 '88 SOUTH LEASIDE TO ST CLAIR STATION' '61 AVENUE RD NORTH HIGHWAY 401'
 '939A FINCH EXPRESS TO FINCH STATION via SCARBOROUGH CENTRE STN'
 '14 GLENCAIRN CALEDONIA'
 '903A KENNEDY STN-SCARB EXPRESS TO CENTENNIAL COLLEGE via SCARBOROUGH CENTRE STN'
 '97C YONGE TO UNION STATION'
 '79A SCARLETT RD RUNNYMEDE STN via FOXWELL/PRITCHARD'
 '352 LAWRENCE WEST BLUE NIGHT SUNNYBROOK HOSPITAL'
 '363 OSSINGTON BLUE NIGHT TO CEDARVALE STATION'
 '110S ISLINGTON SOUTH SHORT TURN TO ISLINGTON & BIRMINGHAM'
 '505 DUNDAS BROADVIEW' '320 YONGE BLUE NIGHT QUEENS QUAY'
 '25C DON MILLS STEELES' "13A AVENUE RD QUEEN'S PARK"
 '43B KENNEDY TO SCARBOROUGH CENTRE STN via PROGRESS'
 '156 MILLWOOD TO WICKSTEED via LAIRD STATION'
 '939C FINCH EXPRESS TO MORNINGSIDE HEIGHTS'
 '508 LAKE SHORE TO LONG BRANCH'
 '18A CALEDONIA TO YORKDALE STATION via BRIDGELAND'
 '53S STEELES EAST SHORT TURN WARDEN'
 '385 SHEPPARD EAST BLUE NIGHT SHEPPARD-YONGE STN'
 '120 CALVINGTON TO WILSON STATION'
 '101S DOWNSVIEW PARK SHORT TURN TO STANLEY GREENE'
 '938 HIGHLAND CREEK EXPRESS TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '25B DON MILLS TO DON MILLS STATION via DON VALLEY STATION'
 '124 SUNNYBROOK TO LAWRENCE STATION' '509 HARBOURFRONT SHORT TURN'
 '78 ST ANDREWS YORK MILLS STN'
 '939A FINCH EXPRESS TO KENNEDY STATION via SCARBOROUGH CENTRE STN'
 '120S CALVINGTON SHORT TURN'
 '334A EGLINTON BLUE NIGHT TO PEARSON AIRPORT via MOUNT DENNIS STATION'
 '51A LESLIE TO LESLIE STATION via LAIRD STATION'
 '39C FINCH EAST VICTORIA PARK and GORDON BAKER'
 '184 ANCASTER PARK TO DE HAVILLAND'
 '905A EGLINTON EAST EXPRESS TO CONLINS via U of T SCARBOROUGH'
 '939S FINCH EXPRESS SHORT TURN' '125 DREWRY FINCH STN'
 '111 EAST MALL EGLINTON'
 '167A PHARMACY NORTH DON MILLS STN via CONSUMERS RD'
 '167A PHARMACY NORTH STEELES via CONSUMERS RD'

In [825]:
# its weird that arrival_time and departure_time are object dtypes instead of a datetime dtype

# lets look at the distribution of values in the arrival_time and departure_time columns
print("Distribution of arrival_time column in stop_times dataframe:")
print(stop_times["arrival_time"].value_counts(dropna=False))
print("-" * 50)
print("Distribution of departure_time column in stop_times dataframe:")
print(stop_times["departure_time"].value_counts(dropna=False))
print("-" * 50)

# lets look at the range of values in the arrival_time and departure_time columns 
print("Range of arrival_time column in stop_times dataframe:")
print(stop_times["arrival_time"].min(), "to", stop_times["arrival_time"].max())
print("-" * 50)
print("Range of departure_time column in stop_times dataframe:")
print(stop_times["departure_time"].min(), "to", stop_times["departure_time"].max())
print("-" * 50)

# so it seems that the arrival_time and departure_time columns record time since the start of service day, in a HH:MM:SS format
# this time can exceed the 24 hour mark since some trips can run past midnight so some arrival and departure times can be greater than 
# 24:00:00 (for example 25:30:00 would mean 1:30am the next day)

# lets see if there is a difference between the recorded arrival and depature times for the same stop_time record
display(stop_times[stop_times["arrival_time"] != stop_times["departure_time"]])

# so it seems that schedule built by the TTC assumes instantaneous arrival and departure at stops since all records have the same arrival
# and departure times

# I will keep the HH:MM:SS format for the arrival_time and departure_time columns since it is a standard format for recording time in GTFS feeds,
# and it can be easily converted to a datetime format if needed for analysis

Distribution of arrival_time column in stop_times dataframe:
arrival_time
25:00:00    461
12:00:00    425
19:10:00    413
19:00:00    411
10:00:00    409
           ...
28:29:44      1
29:11:49      1
29:10:06      1
29:06:30      1
28:55:41      1
Name: count, Length: 92155, dtype: int64
--------------------------------------------------
Distribution of departure_time column in stop_times dataframe:
departure_time
25:00:00    461
12:00:00    425
19:10:00    413
19:00:00    411
10:00:00    409
           ...
28:29:44      1
29:11:49      1
29:10:06      1
29:06:30      1
28:55:41      1
Name: count, Length: 92155, dtype: int64
--------------------------------------------------
Range of arrival_time column in stop_times dataframe:
03:28:00 to 30:46:41
--------------------------------------------------
Range of departure_time column in stop_times dataframe:
03:28:00 to 30:46:41
--------------------------------------------------

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, timepoint]
Index: []

In [826]:
# it is also weird that timepoint is a float dtype when it should be an int dtype (0 vs 1)

# lets display the frequencies of unique values in the timepoint column to see if it only takes the values 0 and 1 as expected
print("Distribution of timepoint column in stop_times dataframe:")
print(stop_times["timepoint"].value_counts(dropna=False))
print("-" * 50)

# so there seems to be some records with empty/null timepoint values. According to GTFS documentation, "All records of stop_times.txt with 
# defined arrival or departure times should have timepoint values populated. If no timepoint values are provided, all times are considered exact."
# since the TTC feed provides defined arrival and departure times for all stop_time records, we will impute the null values to 1 
# meaning that all stop times are considered exact time points in the schedule

# source: https://gtfs.org/documentation/schedule/reference/#routestxt

stop_times["timepoint"] = stop_times["timepoint"].fillna(1)

# we will also convert the timepoint column to an integer dtype since it should only take the values 0 and 1
stop_times["timepoint"] = stop_times["timepoint"].astype(int)

print("Updated distribution of timepoint column in stop_times dataframe:")
print(stop_times["timepoint"].value_counts(dropna=False))
print("-" * 50)

Distribution of timepoint column in stop_times dataframe:
timepoint
0.0    3801988
1.0     276242
NaN     205764
Name: count, dtype: int64
--------------------------------------------------
Updated distribution of timepoint column in stop_times dataframe:
timepoint
0    3801988
1     482006
Name: count, dtype: int64
--------------------------------------------------

In [827]:
# each dytype seems to be appropriate for the type of data in each column
# lets now look at the distribution of values for each column as well

# for the primary key, we will look at the number of unique values and their frequencies
# for integer columns we will look at the range and possibly mean
# for float values we will look at the range (float values usually will represent geographical coordinates so taking the mean/median doesnt make sense)
# for object/string values we will look at the unique values and their frequencies/mode

# groupby trip_id and stop_sequence to see if there are any duplicate records for the same trip and stop sequence
print(f"Table of unique records for each combination of trip_id and stop_sequence in stop_times dataframe:")
display(stop_times.groupby(["trip_id", "stop_sequence"]).count())

for col in stop_times.columns:
    if col in ["trip_id", "stop_sequence"]:
        print(f"Distribution of {col} column in stop_times dataframe:")
        print(stop_times[col].value_counts(dropna=False))
        print("-" * 50)
    elif stop_times[col].dtype == "int64":
        print(f"Range of {col} column in stop_times dataframe: {stop_times[col].min()} to {stop_times[col].max()}")
        print("-" * 50)
        print(f"Distribution of {col} column in stop_times dataframe:")
        print(stop_times[col].value_counts(dropna=False))
        print("-" * 50)
    elif stop_times[col].dtype == "float64":
        print(f"Range of {col} column in stop_times dataframe: {stop_times[col].min()} to {stop_times[col].max()}")
        print("-" * 50)
    elif stop_times[col].dtype == "object":
        print(f"Distribution of {col} column in stop_times dataframe:")
        print(stop_times[col].value_counts(dropna=False))
        print("-" * 50)

Table of unique records for each combination of trip_id and stop_sequence in stop_times dataframe:

                         arrival_time  departure_time  stop_id  stop_headsign  \
trip_id   stop_sequence
1080      1                         1               1        1              1
          2                         1               1        1              1
          3                         1               1        1              1
          4                         1               1        1              1
          5                         1               1        1              1
...                               ...             ...      ...            ...
133251420 14                        1               1        1              0
          15                        1               1        1              0
          16                        1               1        1              0
          17                        1               1        1              0
          18                        1               1        1              0

                         pickup_type  drop_off_type  shape_dist_traveled  \
trip_id   stop_sequence
1080      1                        1              1                    1
          2                        1              1                    1
          3                        1              1                    1
          4                        1              1                    1
          5                        1              1                    1
...                              ...            ...                  ...
133251420 14                       1              1                    1
          15                       1              1                    1
          16                       1              1                    1
          17                       1              1                    1
          18                       1              1                    1

                         timepoint
trip_id   stop_sequence
1080      1                      1
          2                      1
          3                      1
          4                      1
          5                      1
...                            ...
133251420 14                     1
          15                     1
          16                     1
          17                     1
          18                     1

[4283994 rows x 8 columns]

Distribution of trip_id column in stop_times dataframe:
trip_id
3179020      131
107399080    130
91239070     130
81494010     130
70041020     130
            ...
18550010       1
60962010       1
93524020       1
84063010       1
29624020       1
Name: count, Length: 135408, dtype: int64
--------------------------------------------------
Distribution of arrival_time column in stop_times dataframe:
arrival_time
25:00:00    461
12:00:00    425
19:10:00    413
19:00:00    411
10:00:00    409
           ...
28:29:44      1
29:11:49      1
29:10:06      1
29:06:30      1
28:55:41      1
Name: count, Length: 92155, dtype: int64
--------------------------------------------------
Distribution of departure_time column in stop_times dataframe:
departure_time
25:00:00    461
12:00:00    425
19:10:00    413
19:00:00    411
10:00:00    409
           ...
28:29:44      1
29:11:49      1
29:10:06      1
29:06:30      1
28:55:41      1
Name: count, Length: 92155, dtype: int64
--------------------------------------------------
Range of stop_id column in stop_times dataframe: 1 to 43166
--------------------------------------------------
Distribution of stop_id column in stop_times dataframe:
stop_id
42916    4704
42330    4092
42568    3512
416      3461
6857     3460
         ...
18311       2
18308       2
2422        2
5688        2
18307       1
Name: count, Length: 9395, dtype: int64
--------------------------------------------------
Distribution of stop_sequence column in stop_times dataframe:
stop_sequence
2      135397
3      134461
4      133797
5      132916
6      130362
        ...
120         8
119         8
130         6
131         6
132         1
Name: count, Length: 132, dtype: int64
--------------------------------------------------
Distribution of stop_headsign column in stop_times dataframe:
stop_headsign
NaN                                                          205764
NOT IN SERVICE                                                75633
95 YORK MILLS YORK MILLS STN                                  40990
165 WESTON RD NORTH STEELES                                   39347
102 MARKHAM RD WARDEN STN                                     37604
                                                              ...
132S MILNER SHORT TURN TO BRENYON WAY                            12
902S MARKHAM RD EXPRESS SHORT TURN TO MARKHAM AND STEELES        10
335S JANE BLUE NIGHT SHORT TURN TO MOUNT DENNIS STATION           7
119S TORBARRIE SHORT TURN TO EMERY STATION                        6
501 QUEEN SHORT TURN                                              4
Name: count, Length: 737, dtype: int64
--------------------------------------------------
Range of pickup_type column in stop_times dataframe: 0 to 1
--------------------------------------------------
Distribution of pickup_type column in stop_times dataframe:
pickup_type
0    4270317
1      13677
Name: count, dtype: int64
--------------------------------------------------
Range of drop_off_type column in stop_times dataframe: 0 to 1
--------------------------------------------------
Distribution of drop_off_type column in stop_times dataframe:
drop_off_type
0    4278555
1       5439
Name: count, dtype: int64
--------------------------------------------------
Range of shape_dist_traveled column in stop_times dataframe: 0.0 to 50677.14
--------------------------------------------------
Range of timepoint column in stop_times dataframe: 0 to 1
--------------------------------------------------
Distribution of timepoint column in stop_times dataframe:
timepoint
0    3801988
1     482006
Name: count, dtype: int64
--------------------------------------------------

In [828]:
# There are some obervations we can make from this

# 1) There are 4283994 rows in the stop_times dataframe and also 4283994 records with a unique combination of trip_id and stop_sequence, so the
#    are no duplicate records for the primary key of the stop_times dataframe

# 2) There are 135412 unique trip_ids in the trips dataframe but there are 135408 unique trip_ids in the stop_times dataframe, so there are
#    4 trip_ids in the trips dataframe that do not have any corresponding stop_times records. These trip_ids are seen below.
#    This may be due to the fact that some trips are scheduled but not currently active or in service, so they do not have any stop times 
#    associated with them yet; or the feed may just be missing stop_times records for these trip_ids.

# 3) There are 9423 unique stop_ids in the stop dataframe but only 9395 unique stop_ids in the stop_times dataframe, so there are 28
#    stop_ids missing in the stop_times dataframe. These stop_ids are seen below. These stops are quite possibly stops on the missing trips
#    excluded from the stop_times dataframe.

# 4) it seems that quite a few stop_headsigns are null for some reason (200k records out of 4.2 million), so to identify the route the trip is
#     taking, we would need to identify the trip_headsign of the corresponding trip_id in the trips dataframe

# 5) Most stops at most times offer pickup and dropoff services to passengers (value 0), but some do not (value 1), this is most likely when
#    the vehicle is performing a deadhead trip (not picking up or dropping off passengers between two scheduled points) or not in service

In [829]:
# find missing trip_ids in stop_times dataframe that are present in trips dataframe
missing_trip_ids = set(trips["trip_id"]) - set(stop_times["trip_id"])
print("Trip_ids present in trips dataframe but missing in stop_times dataframe:")
print(missing_trip_ids)
print("-" * 50)

# find missing stop_ids in stop_times dataframe that are present in stops dataframe
missing_stop_ids = set(stops["stop_id"]) - set(stop_times["stop_id"])
print("Stop_ids present in stops dataframe but missing in stop_times dataframe:")
print(missing_stop_ids)
print("-" * 50)

Trip_ids present in trips dataframe but missing in stop_times dataframe:
{85287020, 77572020, 80262020, 74591020}
--------------------------------------------------
Stop_ids present in stops dataframe but missing in stop_times dataframe:
{42506, 11155, 4635, 43036, 3742, 5429, 3772, 42819, 42825, 18379, 42956, 42957, 42958, 18384, 39379, 39380, 4822, 4823, 4825, 4826, 18396, 18397, 10077, 18399, 18400, 18797, 18798, 7295}
--------------------------------------------------

In [830]:
# lets look at the presence of null values and empty strings in the rows of the stop_times dataframe

print("Number of null values in each column of stop_times dataframe:")
print(stop_times.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of stop_times dataframe:")
object_columns = stop_times.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (stop_times[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

Number of null values in each column of stop_times dataframe:
trip_id                     0
arrival_time                0
departure_time              0
stop_id                     0
stop_sequence               0
stop_headsign          205764
pickup_type                 0
drop_off_type               0
shape_dist_traveled      8291
timepoint                   0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of stop_times dataframe:
arrival_time: 0
departure_time: 0
stop_headsign: 0
--------------------------------------------------

In [831]:
# we know that stop_headsign will have null values but why does shape_dist_traveled have null values?

# lets look at the frequency of unique values in the shape_dist_traveled column
print("Distribution of shape_dist_traveled column in stop_times dataframe:")
print(stop_times["shape_dist_traveled"].value_counts(dropna=False))
print("-" * 50)

# my initial hypothesis is that shape_dist_traveled is null for records first in the stop sequence of a trip. This is because the frequency of trips
# to have an initial distance traveled of 0 should be quite high and then the frequency distribution for indiivudal cumulative distances should be
# much lower since there are many different distances that can be traveled for different trips and stop sequences,
# since there is such a high frequency of null values, it is possible they are just a placeholder for  the distrance traveled value for a first stop

# lets look at some records with null shape_dist_traveled values
print("Records with null shape_dist_traveled values in stop_times dataframe:")
display(stop_times[stop_times["shape_dist_traveled"].isnull()].head(-10))
print("-" * 50)

# lets look at some records with trip_id = 133243013
print("Records with trip_id 133243013 in stop_times dataframe:")
display(stop_times[stop_times["trip_id"] == 133243013].head(10))
print("-" * 50)

# lets look at some records with trip_id = 133250505
print("Records with trip_id 133250505 in stop_times dataframe:")
display(stop_times[stop_times["trip_id"] == 133250505].head(10))
print("-" * 50)

# so from the 10 records shown, all contain a stop_sequence value of 1, so most likely they are the first stop in the stop sequence, and for 
# two of those trips, the first stop in the sequence has a null shape_dist_traveled value.

# lets see if all records with null shape_dist_traveled values have a stop_sequence value of 1
print("Distribution of stop_sequence values for records with null shape_dist_traveled values in stop_times dataframe:")
print(stop_times[stop_times["shape_dist_traveled"].isnull()]["stop_sequence"].value_counts())
print("-" * 50)

# so all records with null shape_dist_traveled values have a stop_sequence value of 1, so it seems that the initial hypothesis was correct 
# so lets impute the null values in the shape_dist_traveled column to 0...
stop_times["shape_dist_traveled"] = stop_times["shape_dist_traveled"].fillna(0)
print("Updated distribution of shape_dist_traveled column in stop_times dataframe:")
print(stop_times["shape_dist_traveled"].value_counts(dropna=False))
print("-" * 50)

Distribution of shape_dist_traveled column in stop_times dataframe:
shape_dist_traveled
0.0000       119525
NaN            8291
38.9837        2102
26.1379        2095
5.3470         1752
              ...
2499.5300         1
2665.0900         1
2807.7900         1
3042.5500         1
1287.7800         1
Name: count, Length: 36321, dtype: int64
--------------------------------------------------
Records with null shape_dist_traveled values in stop_times dataframe:

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
4078230,133243013,10:30:00,10:30:00,15547,1,NaN,0,0,NaN,1
4078280,133243012,09:00:00,09:00:00,15547,1,NaN,0,0,NaN,1
4078330,133243014,12:00:00,12:00:00,15547,1,NaN,0,0,NaN,1
4078351,133243015,13:14:27,13:14:27,11637,1,NaN,0,0,NaN,1
4078381,133243017,15:30:00,15:30:00,15547,1,NaN,0,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...
4283529,133250503,24:27:44,24:27:44,13865,1,NaN,0,0,NaN,1
4283560,133250504,24:32:36,24:32:36,13865,1,NaN,0,0,NaN,1
4283591,133250505,24:37:28,24:37:28,13865,1,NaN,0,0,NaN,1
4283622,133250506,24:42:20,24:42:20,13865,1,NaN,0,0,NaN,1
4283653,133250507,24:47:12,24:47:12,13865,1,NaN,0,0,NaN,1

--------------------------------------------------
Records with trip_id 133243013 in stop_times dataframe:

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
4078230,133243013,10:30:00,10:30:00,15547,1,NaN,0,0,NaN,1
4078231,133243013,10:35:39,10:35:39,15601,2,NaN,0,0,1.7978,1
4078232,133243013,10:37:04,10:37:04,15589,3,NaN,0,0,2.0984,1
4078233,133243013,10:39:12,10:39:12,7980,4,NaN,0,0,2.5513,1
4078234,133243013,10:41:11,10:41:11,8522,5,NaN,0,0,2.9718,1
4078235,133243013,10:42:49,10:42:49,8811,6,NaN,0,0,3.3162,1
4078236,133243013,10:44:18,10:44:18,15602,7,NaN,0,0,3.6315,1
4078237,133243013,10:48:41,10:48:41,265,8,NaN,0,0,4.6768,1
4078238,133243013,10:50:42,10:50:42,7587,9,NaN,0,0,5.1729,1
4078239,133243013,10:51:39,10:51:39,7001,10,NaN,0,0,5.4098,1

--------------------------------------------------
Records with trip_id 133250505 in stop_times dataframe:

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
4283591,133250505,24:37:28,24:37:28,13865,1,NaN,0,0,NaN,1
4283592,133250505,24:41:05,24:41:05,13731,2,NaN,0,0,2.7446,1
4283593,133250505,24:43:57,24:43:57,13733,3,NaN,0,0,4.9228,1
4283594,133250505,24:45:34,24:45:34,13736,4,NaN,0,0,6.1462,1
4283595,133250505,24:46:53,24:46:53,13737,5,NaN,0,0,7.1231,1
4283596,133250505,24:47:53,24:47:53,13740,6,NaN,0,0,7.9361,1
4283597,133250505,24:49:13,24:49:13,13741,7,NaN,0,0,8.4659,1
4283598,133250505,24:50:13,24:50:13,13744,8,NaN,0,0,9.2348,1
4283599,133250505,24:51:32,24:51:32,13745,9,NaN,0,0,9.7841,1
4283600,133250505,24:52:53,24:52:53,13747,10,NaN,0,0,10.3460,1

--------------------------------------------------
Distribution of stop_sequence values for records with null shape_dist_traveled values in stop_times dataframe:
stop_sequence
1    8291
Name: count, dtype: int64
--------------------------------------------------
Updated distribution of shape_dist_traveled column in stop_times dataframe:
shape_dist_traveled
0.0000       127816
38.9837        2102
26.1379        2095
5.3470         1752
10.6211        1095
              ...
2499.5300         1
2665.0900         1
2807.7900         1
3042.5500         1
1144.9700         1
Name: count, Length: 36320, dtype: int64
--------------------------------------------------

In [832]:
# lets re-look at the presence of null values and empty strings in the rows of the stop_times dataframe

print("Number of null values in each column of stop_times dataframe:")
print(stop_times.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of stop_times dataframe:")
object_columns = stop_times.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (stop_times[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

Number of null values in each column of stop_times dataframe:
trip_id                     0
arrival_time                0
departure_time              0
stop_id                     0
stop_sequence               0
stop_headsign          205764
pickup_type                 0
drop_off_type               0
shape_dist_traveled         0
timepoint                   0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of stop_times dataframe:
arrival_time: 0
departure_time: 0
stop_headsign: 0
--------------------------------------------------

#### Shapes.txt

In [833]:
# print data types of shapes dataframe

print("Data types of shapes dataframe:")
print(shapes.dtypes)
print("-" * 50)

Data types of shapes dataframe:
shape_id                object
shape_pt_lat           float64
shape_pt_lon           float64
shape_pt_sequence        int64
shape_dist_traveled    float64
dtype: object
--------------------------------------------------

In [834]:
# lets first identify columns that are not used in the feed and drop them from the dataframe to simplify our analysis
# we can identify these columns by looking at the unique values in each column and seeing if they are all NaN or empty strings

for col in shapes.columns:
    unique_values = shapes[col].unique()
    print(f"Unique values in {col} column of shapes dataframe:")
    print(unique_values)
    print("-" * 50)

Unique values in shape_id column of shapes dataframe:
['shp-100-01' 'shp-100-02' 'shp-100-03' ... '1103678' '1103684' '1103685']
--------------------------------------------------
Unique values in shape_pt_lat column of shapes dataframe:
[43.701911 43.70207  43.702164 ... 43.762777 43.763014 43.76327 ]
--------------------------------------------------
Unique values in shape_pt_lon column of shapes dataframe:
[-79.35283  -79.352713 -79.352644 ... -79.492964 -79.492263 -79.49189 ]
--------------------------------------------------
Unique values in shape_pt_sequence column of shapes dataframe:
[   1    2    3 ... 3068 3069 3070]
--------------------------------------------------
Unique values in shape_dist_traveled column of shapes dataframe:
[ 0.     20.     31.86   ...  7.0991  7.1741  7.5274]
--------------------------------------------------

In [835]:
# before we realized that shape_id had duplicated string and integer values for the same shape_id for Trips, 
# lets check if that is still the case here

print("Unique values in shape_id column of shape dataframe:")
print(shapes["shape_id"].unique().tolist())

# it looks like all shape_id's are strings, but lets just make sure by checking if we get the same id as a string and integer

display(shapes[(shapes["shape_id"] == 1103629)].head(3))
display(shapes[(shapes["shape_id"] == "1103629")].head(3))

# looks like we dont need to worry about redundant records in the shape dataframe due to the same shape_id being represented as both a string and
# integer

Unique values in shape_id column of shape dataframe:

Empty DataFrame
Columns: [shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled]
Index: []

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
1018493,1103629,43.769143,-79.376846,1,0.0000
1018494,1103629,43.769421,-79.375510,2,0.1124
1018495,1103629,43.769658,-79.374399,3,0.2054

In [836]:
# each dytype seems to be appropriate for the type of data in each column
# lets now look at the distribution of values for each column as well

# for the primary key, we will look at the number of unique values and their frequencies
# for integer columns we will look at the range and possibly mean
# for float values we will look at the range (float values usually will represent geographical coordinates so taking the mean/median doesnt make sense)
# for object/string values we will look at the unique values and their frequencies/mode

# groupby shape_id and shape_pt_sequence to see if there are any duplicate records for the same trip and stop sequence
print(f"Table of unique records for each combination of shape_id and shape_pt_sequence in shapes dataframe:")
display(shapes.groupby(["shape_id", "shape_pt_sequence"]).count())

for col in shapes.columns:
    if col in ["shape_id", "shape_pt_sequence"]:
        print(f"Distribution of {col} column in shapes dataframe:")
        print(shapes[col].value_counts(dropna=False))
        print("-" * 50)
    elif shapes[col].dtype == "int64":
        print(f"Range of {col} column in shapes dataframe: {shapes[col].min()} to {shapes[col].max()}")
        print("-" * 50)
        print(f"Distribution of {col} column in shapes dataframe:")
        print(shapes[col].value_counts(dropna=False))
        print("-" * 50)
    elif shapes[col].dtype == "float64":
        print(f"Range of {col} column in shapes dataframe: {shapes[col].min()} to {shapes[col].max()}")
        print("-" * 50)
    elif shapes[col].dtype == "object":
        print(f"Distribution of {col} column in shapes dataframe:")
        print(shapes[col].value_counts(dropna=False))
        print("-" * 50)

Table of unique records for each combination of shape_id and shape_pt_sequence in shapes dataframe:

                              shape_pt_lat  shape_pt_lon  shape_dist_traveled
shape_id   shape_pt_sequence
1101825    1                             1             1                    1
           2                             1             1                    1
           3                             1             1                    1
           4                             1             1                    1
           5                             1             1                    1
...                                    ...           ...                  ...
shp-996-53 1055                          1             1                    1
           1056                          1             1                    1
           1057                          1             1                    1
           1058                          1             1                    1
           1059                          1             1                    1

[1020671 rows x 3 columns]

Distribution of shape_id column in shapes dataframe:
shape_id
shp-334-61    3070
shp-334-58    3036
shp-334-52    3015
shp-334-64    2882
shp-300-97    2805
              ...
shp-63-24       32
1103629         30
shp-79-56       26
shp-55-02       23
1103630         22
Name: count, Length: 1565, dtype: int64
--------------------------------------------------
Range of shape_pt_lat column in shapes dataframe: 43.591495 to 43.90975
--------------------------------------------------
Range of shape_pt_lon column in shapes dataframe: -79.650423 to -79.122627
--------------------------------------------------
Distribution of shape_pt_sequence column in shapes dataframe:
shape_pt_sequence
21      1563
22      1563
23      1562
20      1562
19      1561
        ...
3047       1
3048       1
3050       1
3051       1
3070       1
Name: count, Length: 3070, dtype: int64
--------------------------------------------------
Range of shape_dist_traveled column in shapes dataframe: 0.0 to 50677.14
--------------------------------------------------

In [837]:
# There are some obervations we can make from this

# 1) There are 1020671 rows in the shapes dataframe and also 1020671 records with a unique combination of shape_id and shape_pt_sequence, so there
#    are no duplicate records for the primary key of the shapes dataframe

# 2) as mentioned before it is odd that the shape_id column is an object column but that is just because some of the id's are annotated as 
#    shp-###-##

# 3) The range of shape_pt_lat and shape_pt_lon seem to align with toronto's coordinates, so thats a good sign that the feed information is 
#    complete and accurate. The ranges listed in shapes dataframe is slightly different than those listed on stops (43.591495 to 43.90975 in shapes
#    vs 43.59181 to 43.90975 in stops and -79.650423 to -79.122627 in shapes vs -79.649908 to -79.123111 in stops), but this is fine since in the
#    GTFS documentation, coordinates of stops and shapes may be slightly different 


# 4) It is a bit strange the the most frequent values for shape_pt_sequence is in the 20's and not just 1 (you would think the first points in the
#   sequence would have low number for shape_pt_sequence) (see below)

# 5) The range of the shape_dist_traveled column in the shapes dataframe matches the range of the shape_dist_traveled in the Stop_times dataframe
#    which is a good indicator of data consistency in the feed (0.0 to 50677.14)

In [838]:
# view full distribution of shape_pt_sequence column
print(shapes["shape_pt_sequence"].value_counts(dropna=False).sort_index().to_string())

# so there are 1554 records with a shape_pt_sequence of 1 but 1563 records with shape_pt_sequence of 22
# lets view records whose shape_id has a shape_pt_sequence of 22 but not 1

valid_shape_ids = (
    shapes.groupby("shape_id")["shape_pt_sequence"]
    .apply(lambda x: 22 in x.values and 1 not in x.values)
)

valid_ids = valid_shape_ids[valid_shape_ids].index

print("shape_ids with a shape_pt_sequence of 22 but not 1")
display(shapes[shapes["shape_id"].isin(valid_ids)])

# so it looks like a few unique shapes have a shape_pt_sequence start with not 1 
print("shape_id of shp-334-51")
display(shapes[shapes["shape_id"] == "shp-334-51"])

# for example "shp-334-51" starts with a shape_pt_sequence of 3, so it is technically plausible that non "1" numbers have a higher record-frequency
# count than 1 (shape_pt_sequence values of 1)

shape_pt_sequence
1       1554
2       1556
3       1557
4       1557
5       1559
6       1560
7       1560
8       1560
9       1560
10      1560
11      1560
12      1561
13      1561
14      1561
15      1561
16      1561
17      1561
18      1561
19      1561
20      1562
21      1563
22      1563
23      1562
24      1561
25      1561
26      1561
27      1560
28      1560
29      1560
30      1560
31      1559
32      1559
33      1559
34      1559
35      1559
36      1558
37      1558
38      1558
39      1557
40      1557
41      1555
42      1555
43      1554
44      1554
45      1554
46      1554
47      1554
48      1553
49      1553
50      1553
51      1552
52      1552
53      1551
54      1549
55      1545
56      1543
57      1539
58      1539
59      1538
60      1537
61      1537
62      1536
63      1534
64      1534
65      1532
66      1529
67      1527
68      1526
69      1523
70      1521
71      1518
72      1517
73      1516
74      1515
75      1514
76      1513
77      1512
78      1512
79      1509
80      1507
81      1506
82      1506
83      1506
84      1505
85      1502
86      1499
87      1497
88      1497
89      1497
90      1496
91      1495
92      1494
93      1494
94      1494
95      1492
96      1487
97      1487
98      1487
99      1481
100     1481
101     1481
102     1478
103     1476
104     1476
105     1475
106     1472
107     1468
108     1466
109     1465
110     1464
111     1462
112     1462
113     1461
114     1461
115     1461
116     1459
117     1458
118     1457
119     1456
120     1454
121     1453
122     1452
123     1449
124     1448
125     1443
126     1436
127     1436
128     1435
129     1435
130     1435
131     1433
132     1431
133     1430
134     1429
135     1429
136     1429
137     1429
138     1424
139     1421
140     1420
141     1418
142     1417
143     1416
144     1416
145     1415
146     1414
147     1409
148     1406
149     1406
150     1402
151     1398
152     1397
153     1395
154     1395
155     1392
156     1392
157     1392
158     1390
159     1389
160     1387
161     1382
162     1381
163     1380
164     1377
165     1376
166     1374
167     1372
168     1372
169     1371
170     1371
171     1370
172     1368
173     1367
174     1365
175     1364
176     1363
177     1362
178     1359
179     1357
180     1356
181     1356
182     1356
183     1354
184     1354
185     1353
186     1352
187     1351
188     1351
189     1348
190     1345
191     1344
192     1344
193     1343
194     1342
195     1341
196     1341
197     1340
198     1339
199     1337
200     1337
201     1336
202     1335
203     1333
204     1331
205     1330
206     1324
207     1324
208     1323
209     1321
210     1321
211     1319
212     1316
213     1316
214     1316
215     1316
216     1314
217     1313
218     1312
219     1309
220     1309
221     1309
222     1307
223     1306
224     1305
225     1302
226     1300
227     1298
228     1298
229     1298
230     1298
231     1294
232     1285
233     1283
234     1283
235     1282
236     1280
237     1278
238     1274
239     1272
240     1271
241     1269
242     1269
243     1267
244     1265
245     1263
246     1262
247     1262
248     1262
249     1261
250     1259
251     1257
252     1256
253     1256
254     1255
255     1254
256     1253
257     1253
258     1253
259     1249
260     1247
261     1246
262     1246
263     1244
264     1244
265     1243
266     1240
267     1237
268     1234
269     1233
270     1231
271     1228
272     1228
273     1227
274     1226
275     1224
276     1223
277     1223
278     1220
279     1220
280     1220
281     1218
282     1216
283     1214
284     1214
285     1210
286     1209
287     1205
288     1204
289     1203
290     1203
291     1202
292     1202
293     1199
294     1199
295     1199
296     1197
297     1197
298     1192
299     1188
300     1185
301     1183
302     1181
303     1180
304     1180
305     1179
306     1178
307     1176
308     1176
309     1173
310     1172
311     1170
312     1168
313     1167
314     1165
315     1164
316     1161
317     1160
318     1160
319     1159
320     1155
321     1152
322     1150
323     1149
324     1148
325     1148
326     1147
327     1145
328     1144
329     1144
330     1144
331     1141
332     1141
333     1140
334     1139
335     1136
336     1135
337     1134
338     1134
339     1134
340     1133
341     1133
342     1132
343     1132
344     1130
345     1127
346     1124
347     1124
348     1122
349     1120
350     1117
351     1116
352     1115
353     1112
354     1112
355     1110
356     1108
357     1107
358     1105
359     1105
360     1104
361     1102
362     1098
363     1095
364     1094
365     1093
366     1092
367     1092
368     1089
369     1088
370     1087
371     1086
372     1085
373     1085
374     1085
375     1083
376     1082
377     1081
378     1081
379     1080
380     1077
381     1075
382     1072
383     1071
384     1071
385     1068
386     1066
387     1065
388     1060
389     1059
390     1057
391     1056
392     1055
393     1051
394     1049
395     1048
396     1047
397     1047
398     1044
399     1044
400     1044
401     1041
402     1037
403     1037
404     1037
405     1036
406     1036
407     1034
408     1031
409     1025
410     1022
411     1020
412     1015
413     1015
414     1013
415     1011
416     1011
417     1011
418     1011
419     1011
420     1010
421     1007
422     1006
423     1006
424     1005
425     1004
426     1002
427     1000
428      998
429      995
430      993
431      991
432      991
433      990
434      988
435      987
436      985
437      984
438      983
439      981
440      981
441      980
442      977
443      977
444      977
445      976
446      975
447      973
448      972
449      971
450      970
451      969
452      968
453      966
454      966
455      965
456      965
457      963
458      962
459      959
460      959
461      959
462      959
463      958
464      957
465      957
466      891
467      891
468      891
469      891
470      891
471      889
472      889
473      888
474      888
475      887
476      886
477      886
478      884
479      884
480      884
481      884
482      883
483      882
484      882
485      881
486      881
487      879
488      878
489      878
490      877
491      875
492      874
493      867
494      866
495      863
496      863
497      862
498      862
499      859
500      858
501      857
502      855
503      851
504      848
505      846
506      846
507      843
508      842
509      841
510      838
511      836
512      836
513      836
514      832
515      832
516      832
517      830
518      830
519      829
520      828
521      827
522      824
523      822
524      820
525      819
526      819
527      818
528      818
529      818
530      818
531      818
532      818
533      817
534      816
535      816
536      816
537      816
538      813
539      811
540      811
541      808
542      807
543      806
544      804
545      803
546      802
547      802
548      802
549      800
550      800
551      799
552      797
553      796
554      793
555      792
556      791
557      791
558      789
559      788
560      788
561      788
562      786
563      786
564      786
565      786
566      785
567      784
568      783
569      783
570      783
571      783
572      783
573      783
574      783
575      782
576      780
577      780
578      779
579      776
580      774
581      774
582      773
583      770
584      769
585      767
586      767
587      765
588      765
589      763
590      761
591      759
592      758
593      754
594      754
595      754
596      753
597      752
598      752
599      750
600      749
601      748
602      745
603      744
604      742
605      741
606      740
607      738
608      738
609      737
610      737
611      737
612      735
613      732
614      730
615      730
616      729
617      728
618      727
619      727
620      724
621      722
622      721
623      719
624      718
625      716
626      714
627      712
628      710
629      707
630      706
631      703
632      702
633      701
634      666
635      665
636      664
637      663
638      659
639      658
640      656
641      652
642      651
643      647
644      646
645      643
646      641
647      640
648      636
649      634
650      633
651      633
652      631
653      631
654      631
655      629
656      628
657      627
658      625
659      624
660      622
661      620
662      619
663      615
664      615
665      613
666      612
667      610
668      609
669      609
670      609
671      606
672      606
673      606
674      604
675      604
676      603
677      603
678      600
679      599
680      599
681      599
682      597
683      597
684      597
685      597
686      597
687      592
688      591
689      589
690      588
691      585
692      584
693      582
694      580
695      580
696      580
697      579
698      578
699      577
700      576
701      576
702      575
703      573
704      572
705      571
706      571
707      569
708      568
709      568
710      567
711      566
712      566
713      564
714      563
715      563
716      562
717      562
718      561
719      559
720      558
721      557
722      557
723      557
724      555
725      555
726      554
727      552
728      552
729      552
730      551
731      551
732      549
733      549
734      548
735      547
736      547
737      546
738      545
739      544
740      543
741      540
742      539
743      538
744      535
745      534
746      534
747      533
748      533
749      531
750      531
751      530
752      529
753      527
754      526
755      524
756      524
757      522
758      522
759      519
760      517
761      515
762      514
763      512
764      509
765      507
766      505
767      504
768      501
769      499
770      499
771      497
772      494
773      494
774      493
775      493
776      493
777      491
778      487
779      487
780      487
781      487
782      485
783      484
784      483
785      483
786      482
787      481
788      479
789      478
790      477
791      477
792      474
793      474
794      472
795      471
796      470
797      467
798      466
799      464
800      463
801      463
802      462
803      461
804      461
805      461
806      461
807      461
808      460
809      460
810      460
811      460
812      456
813      456
814      456
815      456
816      456
817      456
818      455
819      454
820      454
821      453
822      453
823      453
824      452
825      450
826      449
827      448
828      447
829      447
830      446
831      446
832      445
833      444
834      443
835      442
836      441
837      440
838      440
839      440
840      439
841      438
842      436
843      435
844      435
845      434
846      433
847      432
848      431
849      429
850      428
851      428
852      427
853      426
854      426
855      426
856      426
857      426
858      424
859      423
860      422
861      422
862      422
863      422
864      418
865      418
866      418
867      416
868      416
869      416
870      415
871      415
872      414
873      413
874      412
875      410
876      410
877      409
878      406
879      404
880      403
881      401
882      400
883      398
884      396
885      395
886      395
887      393
888      392
889      391
890      390
891      389
892      389
893      389
894      386
895      385
896      383
897      382
898      380
899      380
900      380
901      380
902      378
903      375
904      374
905      373
906      372
907      372
908      370
909      369
910      369
911      368
912      368
913      368
914      367
915      367
916      366
917      363
918      362
919      362
920      361
921      361
922      361
923      360
924      359
925      359
926      359
927      357
928      357
929      357
930      356
931      356
932      354
933      354
934      354
935      354
936      353
937      351
938      349
939      349
940      349
941      348
942      348
943      348
944      346
945      346
946      346
947      345
948      344
949      344
950      341
951      341
952      339
953      338
954      337
955      337
956      336
957      335
958      334
959      334
960      334
961      332
962      332
963      332
964      332
965      332
966      332
967      332
968      332
969      331
970      331
971      330
972      330
973      328
974      327
975      327
976      327
977      325
978      325
979      325
980      324
981      323
982      323
983      323
984      323
985      323
986      323
987      323
988      323
989      322
990      322
991      322
992      321
993      321
994      319
995      319
996      319
997      319
998      319
999      318
1000     317
1001     317
1002     316
1003     314
1004     314
1005     314
1006     313
1007     312
1008     312
1009     312
1010     310
1011     309
1012     309
1013     309
1014     307
1015     307
1016     306
1017     306
1018     306
1019     303
1020     303
1021     302
1022     302
1023     300
1024     299
1025     299
1026     297
1027     297
1028     297
1029     296
1030     296
1031     296
1032     294
1033     294
1034     294
1035     294
1036     294
1037     293
1038     293
1039     293
1040     293
1041     293
1042     293
1043     292
1044     291
1045     289
1046     288
1047     287
1048     287
1049     286
1050     286
1051     286
1052     286
1053     286
1054     285
1055     284
1056     282
1057     281
1058     280
1059     280
1060     278
1061     276
1062     275
1063     274
1064     273
1065     273
1066     272
1067     271
1068     271
1069     271
1070     271
1071     270
1072     270
1073     270
1074     269
1075     269
1076     269
1077     269
1078     268
1079     266
1080     266
1081     265
1082     264
1083     264
1084     264
1085     263
1086     262
1087     262
1088     260
1089     260
1090     260
1091     260
1092     260
1093     260
1094     260
1095     259
1096     258
1097     258
1098     258
1099     258
1100     257
1101     256
1102     255
1103     255
1104     255
1105     255
1106     253
1107     250
1108     250
1109     250
1110     249
1111     249
1112     249
1113     249
1114     248
1115     247
1116     247
1117     244
1118     244
1119     244
1120     244
1121     244
1122     243
1123     243
1124     241
1125     241
1126     238
1127     238
1128     237
1129     235
1130     234
1131     234
1132     234
1133     232
1134     232
1135     231
1136     230
1137     228
1138     226
1139     225
1140     224
1141     223
1142     223
1143     222
1144     222
1145     220
1146     219
1147     219
1148     217
1149     217
1150     215
1151     214
1152     213
1153     213
1154     213
1155     210
1156     209
1157     208
1158     208
1159     206
1160     206
1161     205
1162     204
1163     203
1164     203
1165     201
1166     201
1167     199
1168     199
1169     197
1170     197
1171     197
1172     197
1173     197
1174     196
1175     196
1176     195
1177     195
1178     193
1179     193
1180     193
1181     192
1182     192
1183     192
1184     192
1185     192
1186     192
1187     191
1188     190
1189     188
1190     187
1191     187
1192     185
1193     185
1194     184
1195     184
1196     182
1197     181
1198     181
1199     181
1200     181
1201     181
1202     181
1203     181
1204     181
1205     180
1206     180
1207     180
1208     180
1209     180
1210     178
1211     178
1212     178
1213     178
1214     178
1215     177
1216     175
1217     173
1218     173
1219     173
1220     173
1221     172
1222     172
1223     170
1224     169
1225     169
1226     169
1227     169
1228     166
1229     165
1230     165
1231     164
1232     164
1233     163
1234     163
1235     163
1236     162
1237     162
1238     161
1239     161
1240     161
1241     161
1242     161
1243     161
1244     160
1245     160
1246     160
1247     160
1248     159
1249     159
1250     158
1251     157
1252     156
1253     155
1254     155
1255     155
1256     155
1257     155
1258     155
1259     154
1260     154
1261     154
1262     152
1263     152
1264     151
1265     151
1266     150
1267     150
1268     150
1269     150
1270     150
1271     149
1272     149
1273     149
1274     149
1275     149
1276     149
1277     149
1278     149
1279     149
1280     149
1281     149
1282     149
1283     149
1284     149
1285     149
1286     149
1287     149
1288     149
1289     148
1290     147
1291     147
1292     147
1293     146
1294     146
1295     146
1296     143
1297     142
1298     142
1299     140
1300     140
1301     140
1302     140
1303     140
1304     140
1305     140
1306     140
1307     140
1308     139
1309     139
1310     137
1311     137
1312     137
1313     136
1314     135
1315     133
1316     132
1317     132
1318     132
1319     132
1320     131
1321     130
1322     130
1323     130
1324     130
1325     128
1326     128
1327     128
1328     128
1329     128
1330     126
1331     126
1332     126
1333     126
1334     126
1335     126
1336     126
1337     124
1338     124
1339     123
1340     120
1341     118
1342     116
1343     114
1344     114
1345     113
1346     113
1347     111
1348     111
1349     110
1350     110
1351     110
1352     109
1353     108
1354     106
1355     105
1356     105
1357     105
1358     105
1359     104
1360     104
1361     104
1362     104
1363     103
1364     102
1365     102
1366     102
1367     102
1368     102
1369     102
1370     101
1371     101
1372     101
1373     101
1374     100
1375     100
1376     100
1377     100
1378     100
1379     100
1380     100
1381     100
1382     100
1383     100
1384     100
1385     100
1386     100
1387      99
1388      99
1389      99
1390      99
1391      99
1392      98
1393      98
1394      98
1395      98
1396      98
1397      98
1398      97
1399      97
1400      97
1401      96
1402      96
1403      96
1404      96
1405      95
1406      95
1407      94
1408      93
1409      93
1410      93
1411      91
1412      90
1413      90
1414      88
1415      88
1416      88
1417      88
1418      88
1419      87
1420      86
1421      86
1422      86
1423      86
1424      85
1425      84
1426      84
1427      84
1428      84
1429      83
1430      83
1431      83
1432      81
1433      79
1434      79
1435      79
1436      79
1437      79
1438      79
1439      79
1440      79
1441      79
1442      79
1443      79
1444      79
1445      79
1446      79
1447      79
1448      79
1449      79
1450      79
1451      78
1452      78
1453      78
1454      78
1455      78
1456      78
1457      78
1458      78
1459      78
1460      78
1461      78
1462      78
1463      77
1464      77
1465      77
1466      77
1467      76
1468      76
1469      76
1470      75
1471      75
1472      75
1473      74
1474      74
1475      73
1476      73
1477      71
1478      71
1479      71
1480      71
1481      70
1482      70
1483      70
1484      69
1485      68
1486      68
1487      68
1488      68
1489      68
1490      68
1491      67
1492      66
1493      66
1494      66
1495      66
1496      66
1497      65
1498      65
1499      64
1500      64
1501      64
1502      64
1503      64
1504      64
1505      64
1506      64
1507      64
1508      64
1509      64
1510      64
1511      64
1512      64
1513      64
1514      64
1515      64
1516      63
1517      63
1518      63
1519      63
1520      63
1521      63
1522      63
1523      62
1524      62
1525      62
1526      62
1527      62
1528      62
1529      62
1530      62
1531      62
1532      62
1533      62
1534      62
1535      62
1536      62
1537      62

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
367032,shp-334-51,43.681991,-79.610686,3,40.00
367033,shp-334-51,43.682027,-79.610636,4,45.68
367034,shp-334-51,43.682056,-79.610583,5,51.02
367035,shp-334-51,43.682118,-79.610468,6,62.55
367036,shp-334-51,43.682171,-79.610386,7,71.39
...,...,...,...,...,...
858336,shp-952-04,43.687240,-79.621414,101,1531.69
858337,shp-952-04,43.687070,-79.621329,102,1551.69
858338,shp-952-04,43.687022,-79.621305,103,1557.42
858339,shp-952-04,43.686911,-79.621109,104,1577.42
858340,shp-952-04,43.686811,-79.620932,105,1595.50

shape_id of shp-334-51

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
367032,shp-334-51,43.681991,-79.610686,3,40.00
367033,shp-334-51,43.682027,-79.610636,4,45.68
367034,shp-334-51,43.682056,-79.610583,5,51.02
367035,shp-334-51,43.682118,-79.610468,6,62.55
367036,shp-334-51,43.682171,-79.610386,7,71.39
...,...,...,...,...,...
367123,shp-334-51,43.687364,-79.621110,94,1457.65
367124,shp-334-51,43.687218,-79.621060,95,1474.37
367125,shp-334-51,43.687043,-79.621005,96,1494.37
367126,shp-334-51,43.686867,-79.620950,97,1514.37
367127,shp-334-51,43.686811,-79.620932,98,1520.78

In [839]:
# lets look at the presence of null values and empty strings in the rows of the shapes dataframe

print("Number of null values in each column of shapes dataframe:")
print(shapes.isnull().sum())
print("-" * 50)

print("Number of empty strings in object dtype columns of shapes dataframe:")
object_columns = shapes.select_dtypes(include=["object"]).columns
for col in object_columns:
    num_empty_strings = (shapes[col] == "").sum()
    print(f"{col}: {num_empty_strings}")
print("-" * 50)

# looks like the feed is complete

Number of null values in each column of shapes dataframe:
shape_id               0
shape_pt_lat           0
shape_pt_lon           0
shape_pt_sequence      0
shape_dist_traveled    0
dtype: int64
--------------------------------------------------
Number of empty strings in object dtype columns of shapes dataframe:
shape_id: 0
--------------------------------------------------

#### Calendar.txt

In [ ]:
print("Data types of calendar dataframe:")
print(calendar.dtypes)
print("-" * 50)

print("Data types of calendar_dates dataframe:")
print(calendar_dates.dtypes)
print("-" * 50)

print("Data types of route_types dataframe:")
print(route_types.dtypes)
print("-" * 50)

Data types of calendar dataframe:
service_id    int64
monday        int64
tuesday       int64
wednesday     int64
thursday      int64
friday        int64
saturday      int64
sunday        int64
start_date    int64
end_date      int64
dtype: object
--------------------------------------------------
Data types of agency dataframe:
agency_id           int64
agency_name        object
agency_url         object
agency_timezone    object
agency_lang        object
agency_phone       object
agency_fare_url    object
agency_email       object
cemv_support        int64
dtype: object
--------------------------------------------------
Data types of calendar_dates dataframe:
service_id        int64
date              int64
exception_type    int64
dtype: object
--------------------------------------------------
Data types of route_types dataframe:
Code              object
Transport_Mode    object
Service_Type      object
Sch_Avail         object
DirectionName     object
dtype: object
--------------------------------------------------
Data types of feed_info dataframe:
feed_publisher_name    object
feed_publisher_url     object
feed_lang              object
feed_start_date         int64
feed_end_date           int64
feed_version           object
dtype: object
--------------------------------------------------